//! Print the header generated by this Cargo build, without modifying the checkout.
use std::io::{self, Write};

fn main() -> io::Result<()> {
    io::stdout()
        .lock()
        .write_all(include_bytes!(concat!(env!("OUT_DIR"), "/h3.h")))
}
