//! CPU interoperability tests. Fixtures are generated by the pinned upstream code;
//! see tests/fixtures/refmod/README.md for provenance.
use h3_hrx::{
    refmod::{ApplyOptions, RefMod, RefModMember},
    LatentGrid, Reference,
};
use safetensors::{
    tensor::{serialize, Dtype, TensorView},
    SafeTensors,
};
use serde_json::{json, Value};
use std::{collections::HashMap, path::PathBuf};

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/refmod")
        .join(name)
}
fn write(
    meta: Value,
    dtype: Dtype,
    shape: Vec<usize>,
    data: &[u8],
    dir: &std::path::Path,
) -> PathBuf {
    let view = TensorView::new(dtype, shape, data).unwrap();
    let bytes = serialize(
        [("latent", view)],
        Some(HashMap::from([("refmod_meta".into(), meta.to_string())])),
    )
    .unwrap();
    let path = dir.join("test.safetensors");
    std::fs::write(&path, bytes).unwrap();
    path
}
#[test]
fn upstream_bundle_decodes_audio_in_native_channel_order() {
    let mods = RefMod::load(fixture("combined.safetensors")).unwrap();
    assert_eq!(mods.members().len(), 2);
    assert_eq!(mods.token_count().unwrap(), 18 + 38);
    let audio = &mods.members()[1];
    for s in 0..2 {
        for c in 0..32 {
            for t in 0..19 {
                let upstream = ((c * 2 + s) * 19 + t) % 53;
                assert_eq!(
                    audio.values()[(s * 32 + c) * 19 + t],
                    (upstream as f32 - 26.) / 16.
                );
            }
        }
    }
    let refs = mods.prepare(ApplyOptions::default()).unwrap();
    assert!(matches!(refs.references()[0], Reference::Video { .. }));
    assert!(matches!(refs.references()[1], Reference::Audio { .. }));
}
#[test]
fn exports_have_upstream_tensor_keys_metadata_and_audio_layout() {
    let dir = tempfile::tempdir().unwrap();
    for name in ["visual.safetensors", "combined.safetensors"] {
        let mods = RefMod::load(fixture(name)).unwrap();
        let output = dir.path().join(name);
        mods.save(&output, false).unwrap();
        let bytes = std::fs::read(&output).unwrap();
        let tensors = SafeTensors::deserialize(&bytes).unwrap();
        let original = std::fs::read(fixture(name)).unwrap();
        let expected = SafeTensors::deserialize(&original).unwrap();
        for key in expected.names() {
            assert_eq!(
                tensors.tensor(key).unwrap().data(),
                expected.tensor(key).unwrap().data()
            );
        }
        let restored = RefMod::load(&output).unwrap();
        assert_eq!(restored.token_count().unwrap(), mods.token_count().unwrap());
        for (a, b) in restored.members().iter().zip(mods.members()) {
            assert_eq!(a.values(), b.values());
            assert_eq!(a.metadata(), b.metadata());
        }
        assert!(mods.save(&output, false).is_err());
        assert_eq!(std::fs::read(&output).unwrap(), bytes);
        mods.save(&output, true).unwrap();
    }
}
#[test]
fn strength_matches_upstream_and_copies_borrow_storage() {
    let mods = RefMod::load(fixture("combined.safetensors")).unwrap();
    let prepared = mods
        .prepare(ApplyOptions {
            visual_strength: 0.35,
            audio_strength: 0.35,
            copies: 2,
            max_tokens: Some(112),
        })
        .unwrap();
    assert_eq!(prepared.token_count(), 112);
    let refs = prepared.references();
    let bytes = std::fs::read(fixture("strength.safetensors")).unwrap();
    let expected = SafeTensors::deserialize(&bytes).unwrap();
    let Reference::Video {
        latents: visual, ..
    } = refs[0]
    else {
        panic!()
    };
    let Reference::Video { latents: copy, .. } = refs[1] else {
        panic!()
    };
    assert_eq!(visual.as_ptr(), copy.as_ptr());
    let v = expected.tensor("visual_strength").unwrap();
    for (&got, want) in visual.iter().zip(v.data().chunks_exact(2)) {
        let want = half::f16::from_le_bytes(want.try_into().unwrap()).to_f32();
        assert!((got - want).abs() <= 0.001, "{got} != {want}");
    }
    let Reference::Audio { latents: audio, .. } = refs[2] else {
        panic!()
    };
    let a = expected.tensor("audio_strength").unwrap();
    let want = a
        .data()
        .chunks_exact(4)
        .map(|x| f32::from_le_bytes(x.try_into().unwrap()))
        .collect::<Vec<_>>();
    for s in 0..2 {
        for c in 0..32 {
            for t in 0..19 {
                assert!((audio[(s * 32 + c) * 19 + t] - want[(c * 2 + s) * 19 + t]).abs() < 1e-6);
            }
        }
    }
}
#[test]
fn application_filters_members_checks_options_and_effective_budget() {
    let mods = RefMod::load(fixture("combined.safetensors")).unwrap();
    let prepared = mods
        .prepare(ApplyOptions {
            visual_strength: 0.,
            ..Default::default()
        })
        .unwrap();
    assert_eq!(prepared.token_count(), 38);
    assert_eq!(prepared.references().len(), 1);
    assert!(mods
        .prepare(ApplyOptions {
            copies: 0,
            ..Default::default()
        })
        .is_err());
    for v in [f32::NAN, f32::INFINITY, -0.1, 1.1] {
        assert!(mods
            .prepare(ApplyOptions {
                visual_strength: v,
                ..Default::default()
            })
            .is_err());
    }
    assert!(mods
        .prepare(ApplyOptions {
            copies: 2,
            max_tokens: Some(111),
            ..Default::default()
        })
        .is_err());
    assert_eq!(
        mods.prepare(ApplyOptions {
            visual_strength: 0.,
            audio_strength: 0.,
            max_tokens: Some(0),
            ..Default::default()
        })
        .unwrap()
        .token_count(),
        0
    );
}
#[test]
fn malformed_and_legacy_files_fail_without_gpu() {
    let dir = tempfile::tempdir().unwrap();
    let meta = json!({"_format_version":4,"kind":"image","latent_h":2,"latent_w":2,"latent_t":1});
    for mutation in [
        json!({"_format_version":3,"kind":"image"}),
        json!({"_format_version":4,"kind":"image","latent_t":2}),
        json!({"_format_version":4,"kind":"bundle"}),
        json!({"_format_version":5,"kind":"bundle","members":[]}),
    ] {
        let path = write(
            mutation,
            Dtype::F32,
            vec![1, 24, 1, 2, 2],
            &[0; 384],
            dir.path(),
        );
        assert!(RefMod::load(path).is_err());
    }
    let mut nan = vec![0; 384];
    nan[..4].copy_from_slice(&f32::NAN.to_le_bytes());
    assert!(RefMod::load(write(
        meta.clone(),
        Dtype::F32,
        vec![1, 24, 1, 2, 2],
        &nan,
        dir.path()
    ))
    .is_err());
    assert!(RefMod::load(write(
        meta,
        Dtype::F32,
        vec![1, 24, 1, 3, 2],
        &[0; 576],
        dir.path()
    ))
    .is_err());
    let path = dir.path().join("legacy.safetensors");
    let bytes = serialize(
        [(
            "latent",
            TensorView::new(Dtype::F16, vec![1, 24, 1, 2, 2], &[0; 192]).unwrap(),
        )],
        None,
    )
    .unwrap();
    std::fs::write(&path, bytes).unwrap();
    std::fs::write(path.with_extension("json"), "{\"_format_version\":4}").unwrap();
    assert!(RefMod::load(&path)
        .unwrap_err()
        .to_string()
        .contains("legacy"));
    std::fs::write(&path, [1, 2, 3]).unwrap();
    assert!(RefMod::load(path).is_err());
}
#[test]
fn bf16_import_and_unknown_metadata_survive_export() {
    let dir = tempfile::tempdir().unwrap();
    let data = (0..96)
        .flat_map(|i| half::bf16::from_f32(i as f32).to_le_bytes())
        .collect::<Vec<_>>();
    let path = write(
        json!({"_format_version":4,"kind":"image","extension":{"hello":"world"}}),
        Dtype::BF16,
        vec![1, 24, 1, 2, 2],
        &data,
        dir.path(),
    );
    let mods = RefMod::load(path).unwrap();
    assert_eq!(mods.members()[0].values()[47], 47.);
    let output = dir.path().join("out.safetensors");
    mods.save(&output, false).unwrap();
    assert_eq!(
        RefMod::load(output).unwrap().members()[0].metadata()["extension"]["hello"],
        "world"
    );
}
#[test]
fn constructors_reject_invalid_inputs() {
    assert!(RefMod::new("empty", vec![]).is_err());
    assert!(RefModMember::audio("a", vec![0.; 63], 1).is_err());
    assert!(RefModMember::visual(
        "v",
        vec![0.; 96],
        LatentGrid {
            frames: 1,
            height: 3,
            width: 2
        }
    )
    .is_err());
}

#[test]
#[ignore = "requires gfx1151 and cached video/audio VAE checkpoints"]
fn creation_round_trip_matches_direct_encodes() {
    use h3_hrx::refmod::{AudioInput, CreateOptions, ImageInput};
    use h3_hrx::{Clip, Config, Session};
    let resolver = h3_hrx::models::Resolver::new().offline(true);
    let config = Config {
        video_vae: Some(resolver.find(h3_hrx::models::VIDEO_VAE).unwrap()),
        audio_vae: Some(resolver.find(h3_hrx::models::AUDIO_VAE).unwrap()),
        // Creation must not attempt either unrelated checkpoint.
        dit: Some("/absent/dit".into()),
        te: Some("/absent/te".into()),
        ..Config::default()
    };
    // Safety: tests never mutate checkpoints.
    let mut session = unsafe { Session::new(config) }.unwrap();
    let pixels = (0..64 * 64 * 3)
        .map(|i| (i % 251) as u8)
        .collect::<Vec<_>>();
    let samples = (0..1600)
        .map(|i| (i as f32 * 0.01).sin() * 0.1)
        .collect::<Vec<_>>();
    let audio = AudioInput {
        samples: &samples,
        samples_per_channel: 800,
    };
    let options = CreateOptions {
        resolution: 64,
        ..Default::default()
    };
    let images = [ImageInput {
        pixels: &pixels,
        width: 64,
        height: 64,
    }; 2];
    let mods = session
        .create_refmod(&images, Some(audio), &options)
        .unwrap();
    let normalized = h3_hrx::resize::pil_bilinear(&pixels, 64, 64, 64, 64);
    let (direct, _) = session
        .encode_video(Clip {
            pixels: &normalized,
            frames: 1,
            height: 64,
            width: 64,
        })
        .unwrap();
    let expected = direct
        .iter()
        .map(|&x| half::f16::from_f32(x).to_f32())
        .collect::<Vec<_>>();
    for c in 0..24 {
        for t in 0..2 {
            assert_eq!(
                &mods.members()[0].values()[(c * 2 + t) * 16..(c * 2 + t + 1) * 16],
                &expected[c * 16..(c + 1) * 16]
            );
        }
    }
    let (direct_audio, _) = session.encode_audio(&samples, 800).unwrap();
    assert_eq!(mods.members()[1].values(), direct_audio);
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("created.safetensors");
    mods.save(&path, false).unwrap();
    let loaded = RefMod::load(path).unwrap();
    for (a, b) in mods.members().iter().zip(loaded.members()) {
        assert_eq!(a.values(), b.values());
    }
    // A single non-square source must keep its entire frame when /32 rounding
    // changes the target aspect ratio.
    let pixels = (0..49 * 64 * 3)
        .map(|i| (i % 251) as u8)
        .collect::<Vec<_>>();
    let single = session
        .create_refmod(
            &[ImageInput {
                pixels: &pixels,
                width: 49,
                height: 64,
            }],
            None,
            &options,
        )
        .unwrap();
    let normalized = h3_hrx::resize::pil_bilinear(&pixels, 49, 64, 64, 64);
    let (direct, _) = session
        .encode_video(Clip {
            pixels: &normalized,
            frames: 1,
            height: 64,
            width: 64,
        })
        .unwrap();
    assert_eq!(
        single.members()[0].values(),
        direct
            .iter()
            .map(|&v| half::f16::from_f32(v).to_f32())
            .collect::<Vec<_>>()
    );
    assert_eq!(
        single.members()[0].metadata()["h3_hrx_preprocessing"]["crop"],
        "disabled"
    );
}

#[test]
#[ignore = "requires idle gfx1151 and cached ref2va/text encoder checkpoints"]
fn loaded_bundle_denoises_identically_to_direct_references() {
    use h3_hrx::{
        Config, DenoiseParams, Noise, ResidencyPolicy, Sampler, Session, SessionOptions, Tokenizer,
    };
    let mods = RefMod::load(fixture("combined.safetensors")).unwrap();
    let prepared = mods.prepare(ApplyOptions::default()).unwrap();
    let visual = (0..24 * 3 * 4 * 6)
        .map(|i| (i as f32 % 37. - 18.) / 16.)
        .collect::<Vec<_>>();
    let mut audio = vec![0.; 64 * 19];
    for s in 0..2 {
        for c in 0..32 {
            for t in 0..19 {
                audio[(s * 32 + c) * 19 + t] =
                    (((c * 2 + s) * 19 + t) % 53) as f32 / 16. - 26. / 16.;
            }
        }
    }
    let direct = [
        Reference::Video {
            latents: &visual,
            grid: LatentGrid {
                frames: 3,
                height: 4,
                width: 6,
            },
            audio: None,
        },
        Reference::Audio {
            latents: &audio,
            frames: 19,
        },
    ];
    let resolver = h3_hrx::models::Resolver::new().offline(true);
    let config = Config {
        dit: Some(resolver.find(h3_hrx::models::DIT_REF2VA).unwrap()),
        te: Some(resolver.find(h3_hrx::models::TE).unwrap()),
        // Pre-encoded conditioning must never open a VAE.
        video_vae: Some("/absent/video_vae".into()),
        audio_vae: Some("/absent/audio_vae".into()),
        ..Config::default()
    };
    let context = hrx::inference::ModelContext::new(Default::default()).unwrap();
    let automatic_config = Config {
        dit: None,
        ..config.clone()
    };
    // Safety: tests never mutate checkpoints.
    let mut session = unsafe {
        Session::new_in(
            config,
            SessionOptions {
                residency: ResidencyPolicy::StageScoped,
                ..Default::default()
            },
            &context,
        )
    }
    .unwrap();
    let params = DenoiseParams {
        height: 256,
        width: 256,
        frames: 5,
        steps: 2,
        seed: 7,
        sampler: Sampler::Euler,
        ..Default::default()
    };
    let ids = Tokenizer::new()
        .unwrap()
        .encode("a person speaks in a quiet room")
        .unwrap();
    let a = session
        .denoise(&ids, &params, Noise::default(), &direct, &[], None)
        .unwrap();
    let b = session
        .denoise(
            &ids,
            &params,
            Noise::default(),
            &prepared.references(),
            &[],
            None,
        )
        .unwrap();
    assert_eq!(a.video, b.video);
    assert_eq!(a.audio, b.audio);
    // The library default must choose the same Ref2VA checkpoint as the CLI.
    // Consumers such as the Rustler app construct Config::default() once and
    // supply RefMods only later, when they call denoise.
    let mut automatic = unsafe {
        Session::new_in(
            automatic_config,
            SessionOptions {
                residency: ResidencyPolicy::StageScoped,
                ..Default::default()
            },
            &context,
        )
    }
    .unwrap();
    let actual = automatic
        .denoise(
            &ids,
            &params,
            Noise::default(),
            &prepared.references(),
            &[],
            None,
        )
        .unwrap();
    assert!(
        a.video == actual.video,
        "automatic session used the wrong video model"
    );
    assert!(
        a.audio == actual.audio,
        "automatic session used the wrong audio model"
    );
}

#[test]
fn spatial_strength_matches_upstream_on_nondivisible_pooling_grid() {
    let values = (0..24 * 2 * 18 * 20)
        .map(|i| ((i % 37) as f32 - 18.) / 16.)
        .collect();
    let member = RefModMember::visual(
        "irregular",
        values,
        LatentGrid {
            frames: 2,
            height: 18,
            width: 20,
        },
    )
    .unwrap();
    let mods = RefMod::new("irregular", vec![member]).unwrap();
    let prepared = mods
        .prepare(ApplyOptions {
            visual_strength: 0.35,
            ..Default::default()
        })
        .unwrap();
    let refs = prepared.references();
    let Reference::Video { latents, .. } = refs[0] else {
        panic!()
    };
    let bytes = std::fs::read(fixture("strength.safetensors")).unwrap();
    let expected = SafeTensors::deserialize(&bytes)
        .unwrap()
        .tensor("irregular_strength")
        .unwrap();
    for (&got, want) in latents.iter().zip(expected.data().chunks_exact(2)) {
        let want = half::f16::from_le_bytes(want.try_into().unwrap()).to_f32();
        assert!((got - want).abs() <= 0.001, "{got} != {want}");
    }
}

#[test]
fn standalone_audio_round_trips_without_visual_members() {
    let bundle = RefMod::load(fixture("combined.safetensors")).unwrap();
    let audio = RefMod::new("audio", vec![bundle.members()[1].clone()]).unwrap();
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("audio.safetensors");
    audio.save(&path, false).unwrap();
    let loaded = RefMod::load(&path).unwrap();
    assert_eq!(loaded.metadata()["_format_version"], 4);
    assert_eq!(loaded.members().len(), 1);
    assert_eq!(loaded.members()[0].values(), bundle.members()[1].values());
}

#[test]
#[ignore = "requires gfx1151 and the cached audio VAE checkpoint"]
fn audio_creation_preserves_channels_across_chunks_and_truncation() {
    use h3_hrx::refmod::{AudioInput, CreateOptions};
    use h3_hrx::{Config, Session};
    let resolver = h3_hrx::models::Resolver::new().offline(true);
    let config = Config {
        audio_vae: Some(resolver.find(h3_hrx::models::AUDIO_VAE).unwrap()),
        video_vae: Some("/absent/video_vae".into()),
        dit: Some("/absent/dit".into()),
        te: Some("/absent/te".into()),
        ..Config::default()
    };
    // Safety: the test never writes checkpoints.
    let mut session = unsafe { Session::new(config) }.unwrap();
    let n = 320800;
    let samples = (0..2 * n)
        .map(|i| ((i % n) as f32 * 0.0123).sin() * if i < n { 0.1 } else { 0.2 })
        .collect::<Vec<_>>();
    let input = AudioInput {
        samples: &samples,
        samples_per_channel: n,
    };
    let options = CreateOptions::default();
    let full = session.create_refmod(&[], Some(input), &options).unwrap();
    assert_eq!(full.members()[0].shape(), &[1, 32, 2, 401]);
    let mut tail = samples[320000..n].to_vec();
    tail.extend_from_slice(&samples[n + 320000..]);
    let (expected, frames) = session.encode_audio(&tail, 800).unwrap();
    assert_eq!(frames, 1);
    for (channel, &value) in expected.iter().enumerate() {
        assert_eq!(full.members()[0].values()[channel * 401 + 400], value);
    }
    let mut options = CreateOptions {
        audio_max_tokens: 801,
        ..options
    };
    assert!(session.create_refmod(&[], Some(input), &options).is_err());
    options.truncate_audio = true;
    let truncated = session.create_refmod(&[], Some(input), &options).unwrap();
    assert_eq!(truncated.members()[0].shape(), &[1, 32, 2, 400]);
    for channel in 0..64 {
        assert_eq!(
            &truncated.members()[0].values()[channel * 400..(channel + 1) * 400],
            &full.members()[0].values()[channel * 401..channel * 401 + 400]
        );
    }
}
