"""Generate a bounded seven-tap audio convolution load schedule.

Group eight input channels by tap under workgroup-uniform validity guards;
retain the existing packed layout and ascending channel/tap FP32 FMAs.
"""
from pathlib import Path
import re
from generate_conv_lane import generate
U = 8
ROOT = Path(__file__).resolve().parents[1]
s = generate(U)
a=s.index('  %result0 = scf.for');body=s[a:];head=s[:a]
head+='''  %block_end0 = index.add %base, %last : index
  %length_last = index.sub %length, %one : index
  %end_past = index.cmp ugt, %block_end0, %length_last : index
  %block_end = scf.select %end_past, %length_last, %block_end0 : index
  %right_bound = index.add %length, %pad : index
'''
for k in range(11):
 head+=f'''  %first_shift{k} = index.add %base, %shift{k} : index
  %last_shift{k} = index.add %block_end, %shift{k} : index
  %any_left{k} = index.cmp uge, %last_shift{k}, %pad : index
  %any_right{k} = index.cmp ult, %first_shift{k}, %right_bound : index
  %any_bounds{k} = scalar.andi %any_left{k}, %any_right{k} : i1
  %any{k} = scalar.andi %any_bounds{k}, %tl{k} : i1
'''
start=body[:body.index('    %u0_off')];loads=body[body.index('    %u0_off'):body.index('    %u0_k0_rawf0')];finish=body[body.index('    %u0_k0_rawf0'):]
lines=[head,start]
for u in range(U):
 block=re.search(r'    %u'+str(u)+r'_off =.*?%u'+str(u)+r'_row =[^\n]+',loads,re.S)[0];lines.append(block)
for k in range(11):
 names=[f'%u{u}_k{k}_{suffix}' for u in range(U) for suffix in ['x','w0']];types=', '.join(['f32']*len(names))
 lines.append('    '+', '.join(names)+f' = scf.if %any{k} -> ({types}) {{')
 for u in range(U):
  block=re.search(r'    %u'+str(u)+'_k'+str(k)+r'_kk =.*?%u'+str(u)+'_k'+str(k)+r'_w0 =[^\n]+',loads,re.S)[0]
  block=re.sub(r'%u\d+_k\d+_\w+',lambda m:'%load_'+m[0][1:],block);lines.append(block)
 lines.append('      scf.yield '+', '.join('%load_'+n[1:] for n in names)+' : '+types+'\n    } else {')
 lines.append('      scf.yield '+', '.join(['%zero']*len(names))+' : '+types+'\n    }')
lines.append(finish)
source = '\n'.join(lines).replace('conv1d4_f32', 'conv1d_k7_f32')
source = source.replace('[range(%value, 1, 11)]', '[range(%value, 7, 7)]')
source = source.replace('// Generated by scripts/generate_conv_prefetch.py. Eight outputs, one sample per lane.',
    '// Generated by scripts/generate_conv_k7.py. Eight-channel, tap-grouped load lookahead.\n'
    '// Skip loads for taps that contribute nowhere in the workgroup. Retain each masked FP32 FMA.')
(ROOT / 'kernels/conv1d_k7_f32.loom').write_text(source)
