"""Generate an unpacked FP32 audio convolution with four-channel prefetch.

One sample per lane keeps enough independent work in flight without spilling.
Hoist padding validity outside the channel loop. Retain ascending channel/tap
FP32 FMAs and residual-plus-bias initialization from conv1d4_f32.
"""
from pathlib import Path
import hashlib

ROOT = Path(__file__).resolve().parents[1]


def generate():
    U, S = 4, 1
    original = (ROOT / "kernels/conv1d4_f32.loom").read_text()
    if hashlib.sha256(original.encode()).hexdigest() != "29e0ade578506f55ea302b0997bf3f3c9a69c03875792c6a8bdd4174df645901":
        raise ValueError("Original convolution changed: revalidate layout and arithmetic")
    s = original.replace("index.constant 256 : index", "index.constant 64 : index").replace("index.constant 255 : index", "index.constant 63 : index")
    s = s.replace("@h3.conv1d4_f32.cin : %value: index where [range(%value, 1, 4096)]", "@h3.conv1d4_f32.cin : %value: index where [range(%value, 4, 16), mul(%value, 4)]")
    s = s.replace("@h3.conv1d4_f32.cout : %value: index where [range(%value, 1, 4096)]", "@h3.conv1d4_f32.cout : %value: index where [range(%value, 1, 16)]")
    s = s.replace("@h3.conv1d4_f32.ksize : %value: index where [range(%value, 1, 64)]", "@h3.conv1d4_f32.ksize : %value: index where [range(%value, 1, 11)]")
    lines=[s[:s.index('  %offset1 =')]];a=lines.append
    for k in range(11):
     a(f'''  %tap{k} = index.constant {k} : index
      %live{k} = index.cmp ult, %tap{k}, %ksize : index
      %safe_k{k} = scf.select %live{k}, %tap{k}, %c0 : index
      %shift{k} = index.mul %tap{k}, %dilation : index''')
     for t in range(S):
      a(f'''  %pos{t}_{k} = index.add %n{t}, %shift{k} : index
      %raw{t}_{k} = index.sub %pos{t}_{k}, %pad : index
      %left{t}_{k} = index.cmp uge, %pos{t}_{k}, %pad : index
      %right{t}_{k} = index.cmp ult, %raw{t}_{k}, %len_b : index
      %bounds{t}_{k} = scalar.andi %left{t}_{k}, %right{t}_{k} : i1
      %active{t}_{k} = scalar.andi %active{t}, %live{k} : i1
      %valid{t}_{k} = scalar.andi %bounds{t}_{k}, %active{t}_{k} : i1
      %safe_n{t}_{k} = scf.select %valid{t}_{k}, %raw{t}_{k}, %c0 : index''')
    names=lambda tag:', '.join(f'%{tag}{t}' for t in range(S));types=', '.join(['f32']*S)
    a(f'  %chunk = index.constant {U} : index')
    a('  '+names('result')+' = scf.for %ib = [%c0 to %cin step %chunk]('+', '.join(f'%acc{t} = %start{t} : f32' for t in range(S))+f') -> ({types}) {{')
    for u in range(U):
     a(f'''    %u{u} = index.constant {u} : index
        %i_raw{u} = index.add %ib, %u{u} : index
        %i{u} = index.assume %i_raw{u} [lt(%i_raw{u}, %cin)] : index
        %row{u} = index.mul %i{u}, %ksize : index''')
     for k in range(11):
      a(f'''    %k{u}_{k} = index.assume %safe_k{k} [lt(%safe_k{k}, %ksize)] : index
        %t_raw{u}_{k} = index.add %row{u}, %k{u}_{k} : index
        %t{u}_{k} = index.assume %t_raw{u}_{k} [lt(%t_raw{u}_{k}, %taps)] : index
        %w{u}_{k} = view.load %w_view[%o, %t{u}_{k}] : view<[%cout]x[%taps]xf32> -> f32''')
      for t in range(S):
       a(f'''    %src{u}_{k}_{t} = index.assume %safe_n{t}_{k} [range(%safe_n{t}_{k}, 0, 4194304), lt(%safe_n{t}_{k}, %len_b)] : index
        %x{u}_{k}_{t} = view.load %x_view[%i{u}, %src{u}_{k}_{t}] : view<[%cin]x[%len_b]xf32> -> f32''')
    previous='acc'
    for u in range(U):
     for k in range(11):
      tag=f'f{u}_{k}_'
      for t in range(S):
       a(f'''    %raw_f{u}_{k}_{t} = scalar.fmaf %w{u}_{k}, %x{u}_{k}_{t}, %{previous}{t} : f32
        %{tag}{t} = scf.select %valid{t}_{k}, %raw_f{u}_{k}_{t}, %{previous}{t} : f32''')
      previous=tag
    a('    scf.yield '+names(previous)+' : '+types+'\n  }')
    for t in range(S):
     a(f'''  scf.if %active{t} {{
        %nn = index.assume %n{t} [lt(%n{t}, %len_b)] : index
        view.store %result{t}, %out_view[%o, %nn] : f32, view<[%cout]x[%len_b]xf32>
      }}''')
    a('  kernel.return\n}')
    source = "\n".join(lines).replace("conv1d4_f32", "conv1d_narrow_f32").replace("%c256", "%span").replace("%c255", "%tail")
    source = source[source.index("amdgpu.target"):]
    return "// Generated by scripts/generate_conv_narrow.py. One sample per lane; unpacked weights.\n// Four-channel prefetch, hoisted padding checks, original channel/tap FP32 FMAs.\n" + source + "\n"


if __name__ == "__main__":
    (ROOT / "kernels/conv1d_narrow_f32.loom").write_text(generate())
