"""Generate the decoder's fused FP32 Snake/FIR tile.

Copy the qualified upsample arithmetic verbatim; use cooperative replicated
halos in LDS to preserve the intermediate FP32 boundary and final tap order.
The separate stages remain independent regression references.
"""
from pathlib import Path
import re
import hashlib
H=Path(__file__).resolve().parents[1]
T, W = 64, 64
L = 2*T+10
up=(H/'kernels/up2_snake_f32.loom').read_text()
if hashlib.sha256(up.encode()).hexdigest() != "7105ae624dd3994a007e16b380fed8dd2b6d1fcd2475b456390db86907990bc2":
    raise ValueError("Upsample/Snake arithmetic changed: requalify the fused operation")
body=up[up.index('    %t_plus ='):up.index('    view.store %y,')]
s=f'''// BigVGAN anti-aliased SnakeBeta, generated by scripts/generate_snake_fused.py.
// Each {W}-lane group produces {T} samples from {L} upsampled values in LDS.
// Clamp the downsample index before evaluating its upsample/Snake value, then
// clamp each original input tap. Keep six ascending FIR FMAs, factor2 and the
// original Snake operations, round through FP32 LDS, then twelve ascending FMAs.
// All lanes reach the barrier, including short/partial tiles. No global temporary.
// x [C][len] -> out [C][len]; bindings must be disjoint.
amdgpu.target<gfx11-generic> @h3_snake_fused_f32_gfx11 {{subgroup_size = 32}}
config.decl @h3.snake_fused_f32.channels : %value: index where [range(%value, 1, 4096)]
config.decl @h3.snake_fused_f32.len_bound : %value: index where [range(%value, 256, 4194304), mul(%value, 256)]
kernel.def target(@h3_snake_fused_f32_gfx11) export("h3_snake_fused_f32") @h3_snake_fused_f32(%len: index) {{
  %c1 = index.constant 1 : index
  %span = index.constant {T} : index
  %tail = index.constant {T-1} : index
  %threads = index.constant {W} : index
  %channels = config.get @h3.snake_fused_f32.channels : index
  %rounded = index.add %len, %tail : index
  %groups = index.div %rounded, %span : index
  kernel.launch.config workgroups(%groups, %channels, %c1) workgroup_size(%threads, %c1, %c1) : index
}} launch(%len: index, %x: buffer, %fir: buffer, %alpha: buffer, %beta: buffer, %out: buffer) {{
  %channels = config.get @h3.snake_fused_f32.channels : index
  %len_bound = config.get @h3.snake_fused_f32.len_bound : index
  %c0 = index.constant 0 : index
  %c1 = index.constant 1 : index
  %c2 = index.constant 2 : index
  %c5 = index.constant 5 : index
  %c12 = index.constant 12 : index
  %c15 = index.constant 15 : index
  %span = index.constant {T} : index
  %shared_count = index.constant {L} : index
  %shared_bytes = index.constant {L*4} : offset
  %c0_offset = index.constant 0 : offset
  %zero = scalar.constant 0.0 : f32
  %two = scalar.constant 2.0 : f32
  %len_b = index.assume %len [range(%len, 1, 4194304), le(%len, %len_bound)] : index
  %olen = index.mul %len_b, %c2 : index
  %olen_last = index.sub %olen, %c1 : index
  %len_last = index.sub %len_b, %c1 : index
  %wg = kernel.workgroup.id<x> : index
  %c_0 = kernel.workgroup.id<y> : index
  %ch = index.assume %c_0 [lt(%c_0, %channels)] : index
  %lane = kernel.workitem.id<x> : index
  %base = index.mul %wg, %span : index
  %base2 = index.mul %base, %c2 : index
  %x_global = buffer.assume.memory_space<global> %x : buffer
  %f_global = buffer.assume.memory_space<global> %fir : buffer
  %a_global = buffer.assume.memory_space<global> %alpha : buffer
  %b_global = buffer.assume.memory_space<global> %beta : buffer
  %out_global = buffer.assume.memory_space<global> %out : buffer
  %x_view = buffer.view %x_global[%c0_offset] : buffer -> view<[%channels]x[%len_b]xf32>
  %f_view = buffer.view %f_global[%c0_offset] : buffer -> view<12xf32>
  %a_view = buffer.view %a_global[%c0_offset] : buffer -> view<[%channels]xf32>
  %b_view = buffer.view %b_global[%c0_offset] : buffer -> view<[%channels]xf32>
  %out_view = buffer.view %out_global[%c0_offset] : buffer -> view<[%channels]x[%len_b]xf32>
  %lds = buffer.alloca<workgroup> align(16) %shared_bytes : buffer
  %lds_view = buffer.view %lds[%c0_offset] : buffer -> view<{L}xf32>
'''
for offset in range(0,L,W):
 tag=f'q{offset}_'
 block=f'''  %offset = index.constant {offset} : index
  %qraw = index.add %lane, %offset : index
  %active = index.cmp ult, %qraw, %shared_count : index
  scf.if %active {{
    %slot = index.assume %qraw [lt(%qraw, %shared_count)] : index
    %global0 = index.add %base2, %slot : index
    %low = index.cmp ult, %global0, %c5 : index
    %global1 = index.sub %global0, %c5 : index
    %global2 = scf.select %low, %c0, %global1 : index
    %high = index.cmp ugt, %global2, %olen_last : index
    %global3 = scf.select %high, %olen_last, %global2 : index
    %mm = index.assume %global3 [lt(%global3, %olen)] : index
'''+body+f'''    view.store %y, %lds_view[%slot] : f32, view<{L}xf32>
  }}
'''
 # Rename only SSA variables defined in this copied block.
 names=set(re.findall(r'(%\w+)\s*=',block))
 block=re.sub(r'%\w+',lambda m:'%'+tag+m[0][1:] if m[0] in names else m[0],block)
 s+=block
s+='''  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)
  %nraw = index.add %base, %lane : index
  %in_tile = index.cmp ult, %lane, %span : index
  %in_len = index.cmp ult, %nraw, %len_b : index
  %active = scalar.andi %in_tile, %in_len : i1
  scf.if %active {
    %n = index.assume %nraw [lt(%nraw, %len_b)] : index
    %lane2 = index.mul %lane, %c2 : index
'''
for k in range(12):
 s+=f'''    %k{k} = index.constant {k} : index
    %pos{k} = index.add %lane2, %k{k} : index
    %safe{k} = index.assume %pos{k} [lt(%pos{k}, %shared_count)] : index
    %f{k} = view.load %f_view[%k{k}] : view<12xf32> -> f32
    %v{k} = view.load %lds_view[%safe{k}] : view<{L}xf32> -> f32
'''
for k in range(12):s+=f'    %sum{k} = scalar.fmaf %f{k}, %v{k}, '+('%zero' if k==0 else f'%sum{k-1}')+' : f32\n'
s+='''    view.store %sum11, %out_view[%ch, %n] : f32, view<[%channels]x[%len_b]xf32>
  }
  kernel.return
}
'''
(H/'kernels/snake_fused_f32.loom').write_text(s)
