"""Generate the short FP32 audio upsampler with four-channel lookahead.

Loads use clamped indices, then select away noncontributing taps after each
FMA. Preserve ascending channel/tap accumulation and the initial FP32 bias.
Requires cin divisible by4, cout divisible by16 and ksize <= 2*stride.
"""
from pathlib import Path
import hashlib

ROOT = Path(__file__).resolve().parents[1]

def generate():
    U = 4
    original = (ROOT / 'kernels/convt1d_block_f32.loom').read_text()
    if hashlib.sha256(original.encode()).hexdigest() != '8a5a69ddb95f49e74cdda235a7b4633ff8a3e544ba95abacafb21770d20ce5f7':
        raise ValueError('Original upsampler changed: revalidate its layout and arithmetic')
    s = original.replace('convt1d_block_f32', 'convt1d_f32')
    s=s.replace('@h3.convt1d_f32.cin : %value: index where [range(%value, 1, 4096)]',f'@h3.convt1d_f32.cin : %value: index where [range(%value, {U}, 4096), mul(%value, {U})]')
    head=s[:s.index('  %acc0_0,')];tail=s[s.index('  scf.if %active0 {'):]
    lines=[head];a=lines.append
    types=', '.join(['f32']*16)
    names=lambda pre:', '.join(f'%{pre}{o}' for o in range(16))
    a(f'  %chunk = index.constant {U} : index')
    # At most two phase taps; the caller checks ksize <= 2*stride.
    for k in [0,1]:
     a(f'''  %kb{k} = index.constant {k} : index
      %shift{k} = index.mul %kb{k}, %stride : index
      %kr{k} = index.add %shift{k}, %phase0 : index
      %tl{k} = index.cmp ult, %kr{k}, %ksize : index
      %left{k} = index.cmp uge, %source0, %kb{k} : index
      %nr{k} = index.sub %source0, %kb{k} : index
      %right{k} = index.cmp ult, %nr{k}, %length : index
      %bounds{k} = scalar.andi %left{k}, %right{k} : i1
      %live{k} = scalar.andi %active0, %tl{k} : i1
      %valid{k} = scalar.andi %bounds{k}, %live{k} : i1''')
    for k in [0,1]:
     a(f"  %safe_k{k} = scf.select %tl{k}, %kr{k}, %z : index")
     a(f"  %safe_n{k} = scf.select %valid{k}, %nr{k}, %z : index")
    def loop(tag,ks):
     args=', '.join(f'%{tag}ai{o} = %bias{o} : f32' for o in range(16))
     a(f'  {names(tag+"result")} = scf.for %{tag}base = [%z to %cin step %chunk]({args}) -> ({types}) {{')
     # Prefetch operands for U channels before their ordered FMAs.
     for u in range(U):
      t=f'{tag}{u}_'
      a(f'''    %{t}off = index.constant {u} : index
        %{t}rawi = index.add %{tag}base, %{t}off : index
        %{t}ii = index.assume %{t}rawi [lt(%{t}rawi, %cin)] : index
        %{t}row = index.mul %{t}ii, %ksize : index''')
      for k in ks:
       v=f'{t}k{k}_'
       a(f'''    %{v}kk = index.assume %safe_k{k} [lt(%safe_k{k}, %ksize)] : index
        %{v}tr = index.add %{t}row, %{v}kk : index
        %{v}tap = index.assume %{v}tr [lt(%{v}tr, %taps)] : index
        %{v}src = index.assume %safe_n{k} [range(%safe_n{k}, 0, 4194304), lt(%safe_n{k}, %length)] : index
        %{v}x = view.load %xv[%{t}ii, %{v}src] : view<[%cin]x[%length]xf32> -> f32''')
       for o in range(0,16,4):
        a(f'    %{v}wv{o} = vector.load %wv[%gy, %{v}tap, %oc{o}] : view<[%gyb]x[%taps]x16xf32> -> vector<4xf32>')
        for j in range(4):a(f'    %{v}w{o+j} = vector.extract %{v}wv{o}[{j}] : vector<4xf32> -> f32')
     prev=tag+'ai'
     for u in range(U):
      for k in ks:
       v=f'{tag}{u}_k{k}_'
       for o in range(16):a(f'    %{v}rawf{o} = scalar.fmaf %{v}w{o}, %{v}x, %{prev}{o} : f32\n    %{v}f{o} = scf.select %valid{k}, %{v}rawf{o}, %{prev}{o} : f32')
       prev=v+'f'
     a(f'    scf.yield {names(prev)} : {types}\n  }}')

    loop('all',[0,1])
    for o in range(16):tail=tail.replace(f'%acc{o}_0',f'%allresult{o}')
    a(tail)
    return '\n'.join(line.rstrip() for line in '\n'.join(lines).splitlines())+'\n'

def main():
    source = generate().replace('convt1d_f32', 'convt1d_prefetch_f32')
    source = '// Generated by scripts/generate_convt_prefetch.py. Four-channel lookahead.\n' + source
    (ROOT / 'kernels/convt1d_prefetch_f32.loom').write_text(source)

if __name__ == '__main__':
    main()
