"""Generate short FP32 convolutions with lanes across channels and time.

Eight neighboring lanes cover the eight packed output channels; 64 threads
cover eight time samples. Prefetch 16 input channels while preserving each
output's original FP32 FMA order and residual-plus-bias initialization.
"""
from pathlib import Path
import hashlib

ROOT = Path(__file__).resolve().parents[1]

def generate(prefetch_channels=16):
    L, U = 8, prefetch_channels
    O=8//L;span=64//L
    original = (ROOT / 'kernels/conv1d_prefetch_f32.loom').read_text()
    if hashlib.sha256(original.encode()).hexdigest() != '391576429420c87d4d997a706a69cfb3c7e67a44cb8258c59d9d02c524961095':
        raise ValueError('Original convolution changed: revalidate layout and arithmetic')
    s = original.replace('conv1d_prefetch_f32', 'conv1d4_f32')
    s=s.replace('[range(%value, 4, 4096), mul(%value, 4)]',f'[range(%value, {U}, 4096), mul(%value, {U})]')
    s=s.replace('%span = index.constant 64',f'%span = index.constant {span}').replace('%tail = index.constant 63',f'%tail = index.constant {span-1}').replace('%last = index.constant 63',f'%last = index.constant {span-1}')
    s=s.replace('  %n = index.add %base, %lane : index',f'''  %channel_lanes = index.constant {L} : index
      %outputs_per_lane = index.constant {O} : index
      %time_lane = index.div %lane, %channel_lanes : index
      %output_lane = index.rem %lane, %channel_lanes : index
      %output_offset = index.mul %output_lane, %outputs_per_lane : index
      %n = index.add %base, %time_lane : index''')
    lines=[s[:s.index('  %oc0 =')]];a=lines.append
    for o in range(O):
     a(f'''  %offset{o} = index.constant {o} : index
      %rawoc{o} = index.add %output_offset, %offset{o} : index
      %oc{o} = index.assume %rawoc{o} [lt(%rawoc{o}, %otile)] : index
      %or{o} = index.add %obase, %oc{o} : index
      %o{o} = index.assume %or{o} [lt(%or{o}, %cout)] : index
      %bias{o} = view.load %bv[%o{o}] : view<[%cout]xf32> -> f32''')
    a('''  %n0 = index.add %n, %z : index
      %active0 = index.cmp ult, %n0, %length : index
      %read0 = scalar.andi %is_acc, %active0 : i1''')
    for o in range(O):
     a(f'''  %prev{o} = scf.if %read0 -> (f32) {{
        %nn = index.assume %n0 [lt(%n0, %length)] : index
        %old = view.load %yv[%o{o}, %nn] : view<[%cout]x[%length]xf32> -> f32
        scf.yield %old : f32
      }} else {{ scf.yield %zero : f32 }}
      %start{o} = scalar.addf %prev{o}, %bias{o} : f32''')
    a(s[s.index('  %kb0 ='):s.index('  %result0,')])
    a(f'  %chunk = index.constant {U} : index')
    types=', '.join(['f32']*O);names=lambda pre:', '.join(f'%{pre}{o}' for o in range(O))
    args=', '.join(f'%ai{o} = %start{o} : f32' for o in range(O))
    a(f'  {names("result")} = scf.for %ib = [%z to %cin step %chunk]({args}) -> ({types}) {{')
    for u in range(U):
     t=f'u{u}_'
     a(f'''    %{t}off = index.constant {u} : index
        %{t}rawi = index.add %ib, %{t}off : index
        %{t}ii = index.assume %{t}rawi [lt(%{t}rawi, %cin)] : index
        %{t}row = index.mul %{t}ii, %ksize : index''')
     for k in range(11):
      v=f'{t}k{k}_'
      a(f'''    %{v}kk = index.assume %safe_k{k} [lt(%safe_k{k}, %ksize)] : index
        %{v}tr = index.add %{t}row, %{v}kk : index
        %{v}tap = index.assume %{v}tr [lt(%{v}tr, %taps)] : index
        %{v}src = index.assume %safe_n{k} [range(%safe_n{k}, 0, 4194304), lt(%safe_n{k}, %length)] : index
        %{v}x = view.load %xv[%{t}ii, %{v}src] : view<[%cin]x[%length]xf32> -> f32''')
      for o in range(O):a(f'    %{v}w{o} = view.load %wv[%gy, %{v}tap, %oc{o}] : view<[%gyb]x[%taps]x8xf32> -> f32')
    prev='ai'
    for u in range(U):
     for k in range(11):
      v=f'u{u}_k{k}_'
      for o in range(O):a(f'    %{v}rawf{o} = scalar.fmaf %{v}w{o}, %{v}x, %{prev}{o} : f32\n    %{v}f{o} = scf.select %valid{k}, %{v}rawf{o}, %{prev}{o} : f32')
      prev=v+'f'
    a(f'    scf.yield {names(prev)} : {types}\n  }}')
    a('  scf.if %active0 {\n    %nn = index.assume %n0 [lt(%n0, %length)] : index')
    for o in range(O):a(f'    view.store %result{o}, %yv[%o{o}, %nn] : f32, view<[%cout]x[%length]xf32>')
    a('  }\n  kernel.return\n}')
    return '\n'.join(line.rstrip() for line in '\n'.join(lines).splitlines())+'\n'

def main():
    source = generate().replace('conv1d4_f32', 'conv1d_lane_f32')
    source = source.replace('// Generated by scripts/generate_conv_prefetch.py. Eight outputs, one sample per lane.',
        '// Generated by scripts/generate_conv_lane.py. Eight channels across lanes, eight time samples.')
    (ROOT / 'kernels/conv1d_lane_f32.loom').write_text(source)

if __name__ == '__main__':
    main()
