"""Generate short FP32 convolutions with four-channel operand lookahead.

Preserve ascending input-channel/tap FMAs and initial residual-plus-bias
rounding. Safe addresses and result selection avoid divergent tap branches.
Requires cin divisible by four, cout divisible by eight, and at most 11 taps.
"""
from pathlib import Path
import hashlib

ROOT = Path(__file__).resolve().parents[1]

def generate():
    U = 4
    original = (ROOT / 'kernels/conv1d_block_f32.loom').read_text()
    if hashlib.sha256(original.encode()).hexdigest() != '2f60928f2cd7d46e03d5a15eb6ef1f8e53a272ec68c246e6fc3b95aca42ab12d':
        raise ValueError('Original convolution changed: revalidate layout and arithmetic')
    s = original.replace('conv1d_block_f32', 'conv1d4_f32')
    s=s.replace('index.constant 128','index.constant 64').replace('index.constant 127','index.constant 63')
    s=s.replace('@h3.conv1d4_f32.cin : %value: index where [range(%value, 1, 4096)]',f'@h3.conv1d4_f32.cin : %value: index where [range(%value, {U}, 4096), mul(%value, {U})]')
    s=s.replace('@h3.conv1d4_f32.ksize : %value: index where [range(%value, 1, 64)]','@h3.conv1d4_f32.ksize : %value: index where [range(%value, 1, 11)]')
    lines=[s[:s.index('  %tc1 =')]];a=lines.append
    suffix=s[s.index('  scf.if %active0 {'):s.index('  scf.if %active1 {')]
    types=', '.join(['f32']*8)
    names=lambda pre:', '.join(f'%{pre}{o}' for o in range(8))
    a(f'  %chunk = index.constant {U} : index')
    for k in range(11):
     a(f'''  %kb{k} = index.constant {k} : index
      %tl{k} = index.cmp ult, %kb{k}, %ksize : index
      %shift{k} = index.mul %kb{k}, %dilation : index
      %pos{k} = index.add %n0, %shift{k} : index
      %raw{k} = index.sub %pos{k}, %pad : index
      %left{k} = index.cmp uge, %pos{k}, %pad : index
      %right{k} = index.cmp ult, %raw{k}, %length : index
      %bounds{k} = scalar.andi %left{k}, %right{k} : i1
      %live{k} = scalar.andi %active0, %tl{k} : i1
      %valid{k} = scalar.andi %bounds{k}, %live{k} : i1
      %safe_k{k} = scf.select %tl{k}, %kb{k}, %z : index
      %safe_n{k} = scf.select %valid{k}, %raw{k}, %z : index''')
    args=', '.join(f'%ai{o} = %start{o}_0 : f32' for o in range(8))
    a(f'  {names("result")} = scf.for %ib = [%z to %cin step %chunk]({args}) -> ({types}) {{')
    for u in range(U):
     t=f'u{u}_'
     a(f'''    %{t}off = index.constant {u} : index
        %{t}rawi = index.add %ib, %{t}off : index
        %{t}ii = index.assume %{t}rawi [lt(%{t}rawi, %cin)] : index
        %{t}row = index.mul %{t}ii, %ksize : index''')
     for k in range(11):
      v=f'{t}k{k}_'
      a(f'''    %{v}kk = index.assume %safe_k{k} [lt(%safe_k{k}, %ksize)] : index
        %{v}tr = index.add %{t}row, %{v}kk : index
        %{v}tap = index.assume %{v}tr [lt(%{v}tr, %taps)] : index
        %{v}src = index.assume %safe_n{k} [range(%safe_n{k}, 0, 4194304), lt(%safe_n{k}, %length)] : index
        %{v}x = view.load %xv[%{t}ii, %{v}src] : view<[%cin]x[%length]xf32> -> f32''')
      for o in range(0,8,4):
       a(f'    %{v}wv{o} = vector.load %wv[%gy, %{v}tap, %oc{o}] : view<[%gyb]x[%taps]x8xf32> -> vector<4xf32>')
       for j in range(4):a(f'    %{v}w{o+j} = vector.extract %{v}wv{o}[{j}] : vector<4xf32> -> f32')
    prev='ai'
    for u in range(U):
     for k in range(11):
      v=f'u{u}_k{k}_'
      for o in range(8):a(f'    %{v}rawf{o} = scalar.fmaf %{v}w{o}, %{v}x, %{prev}{o} : f32\n    %{v}f{o} = scf.select %valid{k}, %{v}rawf{o}, %{prev}{o} : f32')
      prev=v+'f'
    a(f'    scf.yield {names(prev)} : {types}\n  }}')
    for o in range(8):suffix=suffix.replace(f'%result{o}_0',f'%result{o}')
    a(suffix+'  kernel.return\n}')
    return '\n'.join(line.rstrip() for line in '\n'.join(lines).splitlines())+'\n'

def main():
    source = generate().replace('conv1d4_f32', 'conv1d_prefetch_f32')
    source = source.replace('// Eight output channels share two samples per lane; 64 lanes cover 128 samples.',
        '// Generated by scripts/generate_conv_prefetch.py. Eight outputs, one sample per lane.')
    (ROOT / 'kernels/conv1d_prefetch_f32.loom').write_text(source)

if __name__ == '__main__':
    main()
