"""Generate short convolutions with tap-major loads and channel-major FMAs.

Prefetch all sixteen input channels for one tap before loading the next tap.
This exposes independent loads for small filters without changing any output's
FP32 reduction. The three-tap bound keeps register pressure under control.
"""
from pathlib import Path
from generate_conv_lane import generate as generate_lane

ROOT = Path(__file__).resolve().parents[1]


def generate():
    original = generate_lane()
    prefix = original[:original.index('    %u0_off')]
    prefix = prefix.replace(
        'config.decl @h3.conv1d4_f32.ksize : %value: index where [range(%value, 1, 11)]',
        'config.decl @h3.conv1d4_f32.ksize : %value: index where [range(%value, 1, 3)]',
    )
    lines = [prefix]
    for u in range(16):
        lines.append(f'''    %u{u}_off = index.constant {u} : index
    %u{u}_rawi = index.add %ib, %u{u}_off : index
    %u{u}_ii = index.assume %u{u}_rawi [lt(%u{u}_rawi, %cin)] : index
    %u{u}_row = index.mul %u{u}_ii, %ksize : index''')
    for k in range(3):
        for u in range(16):
            v = f'u{u}_k{k}_'
            lines.append(f'''    %{v}kk = index.assume %safe_k{k} [lt(%safe_k{k}, %ksize)] : index
    %{v}tr = index.add %u{u}_row, %{v}kk : index
    %{v}tap = index.assume %{v}tr [lt(%{v}tr, %taps)] : index
    %{v}src = index.assume %safe_n{k} [range(%safe_n{k}, 0, 4194304), lt(%safe_n{k}, %length)] : index
    %{v}x = view.load %xv[%u{u}_ii, %{v}src] : view<[%cin]x[%length]xf32> -> f32
    %{v}w0 = view.load %wv[%gy, %{v}tap, %oc0] : view<[%gyb]x[%taps]x8xf32> -> f32''')
    previous = '%ai0'
    for u in range(16):
        for k in range(3):
            v = f'u{u}_k{k}_'
            lines.append(f'''    %{v}rawf0 = scalar.fmaf %{v}w0, %{v}x, {previous} : f32
    %{v}f0 = scf.select %valid{k}, %{v}rawf0, {previous} : f32''')
            previous = f'%{v}f0'
    lines.append(f'    scf.yield {previous} : f32\n  }}')
    lines.append(original[original.index('  scf.if %active0 {'):])
    source = '\n'.join(lines).replace('conv1d4_f32', 'conv1d_k3_f32')
    source = source.replace(
        '// Generated by scripts/generate_conv_prefetch.py. Eight outputs, one sample per lane.',
        '// Generated by scripts/generate_conv_k3.py. Tap-major loads, original channel/tap FMAs.',
    )
    return source.rstrip() + '\n'


if __name__ == '__main__':
    (ROOT / 'kernels/conv1d_k3_f32.loom').write_text(generate())
