"""Decoder GEMMs: 128x256 tiles and direct padded SwiGLU output."""
from pathlib import Path
import re
import gen_gemm
from gen_gemm_f16 import gemm

ROOT = Path(__file__).resolve().parent.parent


def aspect(mode):
    previous = gen_gemm.TM, gen_gemm.TN, gen_gemm.A_PACKETS
    try:
        gen_gemm.TM, gen_gemm.TN, gen_gemm.A_PACKETS = 128, 256, 2
        source = gemm(gen_gemm.generate(mode, bias=True, gate_first=mode != "swiglu", bits=8))
    finally:
        gen_gemm.TM, gen_gemm.TN, gen_gemm.A_PACKETS = previous
    changes = {
        "%c255 = index.constant 255": "%c255 = index.constant 127",
        "%m_tiles = index.div %m_rounded, %c256": "%m_tiles = index.div %m_rounded, %c128",
        "%n_tiles = index.div %n_size0, %c128": "%n_tiles = index.div %n_size0, %c256",
        "%c_n_tiles = index.div %n_size, %c128": "%c_n_tiles = index.div %n_size, %c256",
        "%wave_m = index.div %subgroup, %c2": "%wave_m = index.div %subgroup, %c4",
        "%wave_n = index.rem %subgroup, %c2": "%wave_n = index.rem %subgroup, %c4",
        "%base_m = index.mul %tile_m_id, %c256": "%base_m = index.mul %tile_m_id, %c128",
        "%base_n = index.mul %tile_n_id, %c128": "%base_n = index.mul %tile_n_id, %c256",
        "range(%value, 128, 65536), mul(%value, 128)": "range(%value, 256, 65536), mul(%value, 256)",
        "range(%n_size0, 128, 65536), mul(%n_size0, 128)": "range(%n_size0, 256, 65536), mul(%n_size0, 256)",
    }
    for old,new in changes.items():
        assert source.count(old) == 1,old
        source=source.replace(old,new)
    return source.replace("gemm_f16_", "gemm_f16_aspect_")

def generate(mode):
    source = aspect(mode).replace("gemm_f16_aspect_", "gemm_f16_fast_")
    # Large row groups improve weight reuse on the 1797-token decoder shapes.
    # The host selects the group per projection; other shapes keep their rule.
    source = source.replace(".m_group : %value: index where [range(%value, 1, 4)]",
                            ".m_group : %value: index where [range(%value, 1, 16)]")
    if mode == "swiglu":
        ns = "h3.gemm_f16_fast_swiglu_256b_gs"
        source = source.replace(f"config.decl @{ns}.m_group", f"config.decl @{ns}.out_stride : %value: index where [range(%value, 128, 65536), mul(%value, 128)]\n\nconfig.decl @{ns}.m_group")
        source = source.replace("%n_half = index.div %n_size, %c2 : index", f"%n_half = index.div %n_size, %c2 : index\n  %out_stride = config.get @{ns}.out_stride : index")
        source = source.replace("view<[%m_bounded]x[%n_half]xf16>", "view<[%m_bounded]x[%out_stride]xf16>")
    # Keep one A packet and one W packet ahead of the WMMAs. Without a fence
    # the scheduler sinks every prefetch after the last multiply. Keeping all
    # six early was slower in the measured kernel; the bounded pair wins.
    late, lines = [], []
    for line in source.splitlines(True):
        name = line.strip().split(" = ")[0]
        if name in ("%na1", "%nw1", "%nw2", "%nw3"):
            late.append(line)
        else:
            lines.append(line)
    assert len(late) == 4
    source = "".join(lines)
    pos = source.index("    %da0_0 =")
    source = source[:pos] + "    scf.schedule.fence\n" + "".join(late) + source[pos:]
    source = re.sub(r"^\s*//[^\n]*\n", "", source, flags=re.M)
    return ("// Biased f16 decoder GEMM: 128x256, eight 64x64 waves, K-step 64.\n"
            "// 55,296 bytes LDS; ascending 16-wide WMMA accumulation.\n"
            "// Two operand packets are prefetched before the WMMAs using a scheduling fence.\n"
            "// SwiGLU supports the down projection's padded output pitch.\n"
            "// Generated by tools/gen_gemm_f16_fast.py.\n" + source)


if __name__ == "__main__":
    for mode in ("plain", "resid", "swiglu"):
        stem = "gemm_f16_fast" + ("" if mode == "plain" else "_" + mode) + "_256b" + ("_gs" if mode == "swiglu" else "")
        (ROOT / "h3/kernels" / f"{stem}.loom").write_text(generate(mode))
