"""Experimental 128x256 workgroup tiles, retaining 64x64 wave tiles.

The production generator uses 256x128. Exchanging the workgroup aspect ratio
doubles reuse of activation rows across output columns, at the cost of less
weight reuse. This changes neither quantization nor accumulation order.
"""

from pathlib import Path

import gen_gemm


def generate(mode):
    previous = gen_gemm.TM, gen_gemm.TN, gen_gemm.A_PACKETS
    try:
        gen_gemm.TM, gen_gemm.TN, gen_gemm.A_PACKETS = 128, 256, 2
        source = gen_gemm.generate(mode, bits=8, suffix="wide")
    finally:
        gen_gemm.TM, gen_gemm.TN, gen_gemm.A_PACKETS = previous
    substitutions = {
        "%c255 = index.constant 255": "%c255 = index.constant 127",
        "%m_tiles = index.div %m_rounded, %c256": "%m_tiles = index.div %m_rounded, %c128",
        "%n_tiles = index.div %n_size0, %c128": "%n_tiles = index.div %n_size0, %c256",
        "%c_n_tiles = index.div %n_size, %c128": "%c_n_tiles = index.div %n_size, %c256",
        "%wave_m = index.div %subgroup, %c2": "%wave_m = index.div %subgroup, %c4",
        "%wave_n = index.rem %subgroup, %c2": "%wave_n = index.rem %subgroup, %c4",
        "%base_m = index.mul %tile_m_id, %c256": "%base_m = index.mul %tile_m_id, %c128",
        "%base_n = index.mul %tile_n_id, %c128": "%base_n = index.mul %tile_n_id, %c256",
        "range(%value, 128, 65536), mul(%value, 128)": "range(%value, 256, 65536), mul(%value, 256)",
        "range(%n_size0, 128, 65536), mul(%n_size0, 128)": "range(%n_size0, 256, 65536), mul(%n_size0, 256)",
    }
    for old, new in substitutions.items():
        if source.count(old) != 1:
            raise ValueError(f"Expected one occurrence: {old}")
        source = source.replace(old, new)
    # Replace the inherited header: its fixed tile and operand comments do not
    # describe this experiment. The suffix retains _256 for generator compatibility.
    source = source[source.index("amdgpu.target") :]
    return (
        "// INT8 GEMM, 128x256 workgroup tile, eight 64x64 waves (2 M x 4 N).\n"
        "// Generated by tools/gen_gemm_i8_wide.py; 30720 bytes LDS.\n" + source
    )


if __name__ == "__main__":
    root = Path(__file__).resolve().parent.parent
    for mode in ("plain", "resid"):
        stem = "gemm_i8wide" + ("_resid" if mode == "resid" else "") + "_256"
        (root / "experiments" / f"{stem}.loom").write_text(generate(mode))
