"""kernels/gemm_i4{,_resid,_swiglu}_256.loom: MiniMax H3's int4 GEMM family on loom-gemm's
64x64-wave-tile kernel (workgroup tile 256x128, 0.5 LDS operand reads per multiply), with the
three epilogues the runtime needs:
  plain  : C[m, n] = f16( acc * w_scale[n] * a_scale[m] )
  resid  : X[m, n] += gate[cls[m]][n] * acc * w_scale[n] * a_scale[m]   (in place on the f32 residual stream)
  swiglu : C[m, o] = f16( silu(g) * u ) with the weight rows interleaved in 16-row gate/up groups
Weights are int4 per output row (A [M][K] and W [N][K] nibbles, low first), i32 accumulation.

    python3 tools/gen_gemm.py            writes the three kernels
GENERATED kernels; edit the generator.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODE = "plain"
TM, TN = 256, 128
WM, WN = 64, 64
FM, FN = WM // 16, WN // 16
V2, V8, V4 = "vector<2xi32>", "vector<8xi32>", "vector<4xi32>"
ACC = [f"{i}{j}" for i in range(FM) for j in range(FN)]
PACKETS = (TM + TN) * 4 // 256
A_PACKETS = TM * 4 // 256


def generate(mode: str) -> str:
    STEM = {"plain": "gemm_i4_256", "resid": "gemm_i4_resid_256", "swiglu": "gemm_i4_swiglu_256"}[mode]
    SYM, NS = "h3_" + STEM, "h3." + STEM
    extra_args = {"plain": "", "resid": ", %gate: buffer, %cls: buffer", "swiglu": ""}[mode]
    extra_cfg = "\nconfig.decl @" + NS + ".m_group : %value: index where [range(%value, 1, 4)]\n" + ("\nconfig.decl @" + NS + ".classes : %value: index where [range(%value, 1, 64)]\n" if mode == "resid" else "")
    K = ""
    K += f"""// int4 GEMM on the gfx11 WMMA with 64x64 wave tiles: C[m, n] = f16(scale[n] * sum_k A[m, k] * W[n, k])
    // with A [M][K] and W [N][K] signed int4 nibbles, low nibble first, i32 accumulation, f32 scale.
    // Workgroup tile {TM}x{TN}, eight waves as 4 (m) x 2 (n) of {WM}x{WN} (4 x 4 accumulator fragments);
    // per 16-wide k sub-step a wave loads 4 A and 4 W runs from the stage and issues 16 WMMAs.
    // One {(TM + TN) * 80}-byte stage ({TM} A rows + {TN} W rows of 80 bytes), packets carried one
    // step ahead in registers, grouped rasterization (4 m-tiles per n sweep).
    //
    // GENERATED by tools/gen_wave64.py; edit the generator.

    amdgpu.target<gfx11-generic> @{SYM}_gfx11 {{subgroup_size = 32}}

    config.decl @{NS}.k_size : %value: index where [range(%value, 128, 65536), mul(%value, 128)]

    config.decl @{NS}.n_size : %value: index where [range(%value, 128, 32768), mul(%value, 128)]
{extra_cfg}
    kernel.def target(@{SYM}_gfx11) export("{SYM}") @{SYM}(%m_size: index) {{
      %c1 = index.constant 1 : index
      %c3 = index.constant 3 : index
      %c4 = index.constant 4 : index
      %c128 = index.constant 128 : index
      %c255 = index.constant 255 : index
      %c256 = index.constant 256 : index
      %n_size0 = config.get @{NS}.n_size : index
      %m_rounded = index.add %m_size, %c255 : index
      %m_tiles = index.div %m_rounded, %c256 : index
      %m_group = config.get @{NS}.m_group : index
      %m_group_less = index.sub %m_group, %c1 : index
      %m_tiles3 = index.add %m_tiles, %m_group_less : index
      %m_groups = index.div %m_tiles3, %m_group : index
      %m_tiles_padded = index.mul %m_groups, %m_group : index
      %n_tiles = index.div %n_size0, %c128 : index
      kernel.launch.config workgroups(%n_tiles, %m_tiles_padded, %c1) workgroup_size(%c256, %c1, %c1) : index
    }} launch(%m_size: index, %a: buffer, %w: buffer, %scale: buffer, %a_scale: buffer, %c: buffer{extra_args}) {{
      %k_size0 = config.get @{NS}.k_size : index
      %n_size0 = config.get @{NS}.n_size : index
      %k_size = index.assume %k_size0 [range(%k_size0, 128, 65536), mul(%k_size0, 128)] : index
      %n_size = index.assume %n_size0 [range(%n_size0, 128, 32768), mul(%n_size0, 128)] : index

      %c0 = index.constant 0 : index
      %c1 = index.constant 1 : index
      %c2 = index.constant 2 : index
      %c3 = index.constant 3 : index
      %c4 = index.constant 4 : index
      %c6 = index.constant 6 : index
      %c8 = index.constant 8 : index
      %c10 = index.constant 10 : index
      %c12 = index.constant 12 : index
      %c14 = index.constant 14 : index
      %c16 = index.constant 16 : index
      %c32 = index.constant 32 : index
      %c48 = index.constant 48 : index
      %c64 = index.constant 64 : index
      %c128 = index.constant 128 : index
      %c192 = index.constant 192 : index
      %c256 = index.constant 256 : index
      %cf0 = index.constant 0 : index
      %cf1 = index.constant 1 : index
      %cf2 = index.constant 2 : index
      %cf3 = index.constant 3 : index
      %cf4 = index.constant 4 : index
      %cf5 = index.constant 5 : index
      %cf6 = index.constant 6 : index
      %cf7 = index.constant 7 : index
      %cf8 = index.constant 8 : index
      %cf9 = index.constant 9 : index
      %cf10 = index.constant 10 : index
      %cf11 = index.constant 11 : index
      %cf12 = index.constant 12 : index
      %cf13 = index.constant 13 : index
      %cf14 = index.constant 14 : index
      %cf15 = index.constant 15 : index
      %c0_offset = index.constant 0 : offset
      %lds_bytes = index.constant {(TM + TN) * 80} : offset
      %w_stage_offset = index.constant {TM * 80} : offset
      %wave_result_bytes = index.constant 2048 : offset
      %m = index.constant 16 : index
      %n = index.constant 16 : index
      %k = index.constant 16 : index
      %zero_i32x8 = vector.constant 0 : vector<8xi32>
      %zero_i32x4 = vector.constant 0 : vector<4xi32>
      %i4_schema = encoding.define #encoding.operand<element_format=i4, payload_elements=16, payload_registers=2> : encoding<schema>

      %workitem = kernel.workitem.id<x> : index
      %subgroup0 = kernel.subgroup.id : index
      %subgroup = index.assume %subgroup0 [range(%subgroup0, 0, 7)] : index
      %lane = kernel.subgroup.lane.id : index
      %lane16 = index.rem %lane, %c16 : index
      %m_bounded = index.assume %m_size [range(%m_size, 1, 16777216)] : index
      %wg_x = kernel.workgroup.id<x> : index
      %wg_y = kernel.workgroup.id<y> : index
      %c_n_tiles = index.div %n_size, %c128 : index
      %linear0 = index.mul %wg_y, %c_n_tiles : index
      %linear = index.add %linear0, %wg_x : index
      %m_group = config.get @{NS}.m_group : index
      %group_span = index.mul %c_n_tiles, %m_group : index
      %group = index.div %linear, %group_span : index
      %in_group = index.rem %linear, %group_span : index
      %group_m = index.mul %group, %m_group : index
      %m_in_group = index.rem %in_group, %m_group : index
      %tile_m_id = index.add %group_m, %m_in_group : index
      %tile_n_id0 = index.div %in_group, %m_group : index
      %tile_n_id = index.assume %tile_n_id0 [lt(%tile_n_id0, %c_n_tiles)] : index

      // Wave grid 4 (m) x 2 (n): rows wave_row..+64, columns wave_col..+64 of the tile.
      %wave_m = index.div %subgroup, %c2 : index
      %wave_n = index.rem %subgroup, %c2 : index
      %wave_row = index.mul %wave_m, %c64 : index
      %wave_col = index.mul %wave_n, %c64 : index
      %base_m = index.mul %tile_m_id, %c256 : index
      %base_n = index.mul %tile_n_id, %c128 : index
      %k_quads = index.div %k_size, %c8 : index

      %a_global = buffer.assume.memory_space<global> %a : buffer
      %w_global = buffer.assume.memory_space<global> %w : buffer
      %scale_global = buffer.assume.memory_space<global> %scale : buffer
      %c_global = buffer.assume.memory_space<global> %c : buffer
      %a_view = buffer.view %a_global[%c0_offset] : buffer -> view<[%m_bounded]x[%k_quads]xi32>
      %w_view = buffer.view %w_global[%c0_offset] : buffer -> view<[%n_size]x[%k_quads]xi32>
      %scale_view = buffer.view %scale_global[%c0_offset] : buffer -> view<[%n_size]xf32>
      %a_scale_global = buffer.assume.memory_space<global> %a_scale : buffer
      %a_scale_view = buffer.view %a_scale_global[%c0_offset] : buffer -> view<[%m_bounded]xf32>
    """
    if mode == "plain":
        K += "      %c_view = buffer.view %c_global[%c0_offset] : buffer -> view<[%m_bounded]x[%n_size]xf16>\n"
    elif mode == "resid":
        K += f"""      %gate_global = buffer.assume.memory_space<global> %gate : buffer
      %cls_global = buffer.assume.memory_space<global> %cls : buffer
      %classes = config.get @{NS}.classes : index
      %gate_view = buffer.view %gate_global[%c0_offset] : buffer -> view<[%classes]x[%n_size]xf32>
      %cls_view = buffer.view %cls_global[%c0_offset] : buffer -> view<[%m_bounded]xi32>
      %c_view = buffer.view %c_global[%c0_offset] : buffer -> view<[%m_bounded]x[%n_size]xf32>
"""
    else:
        K += "      %n_half = index.div %n_size, %c2 : index\n      %c_view = buffer.view %c_global[%c0_offset] : buffer -> view<[%m_bounded]x[%n_half]xf16>\n"
    K += f"""
      %lds = buffer.alloca<workgroup> align(16) %lds_bytes : buffer
      %a_stage = buffer.view %lds[%c0_offset] : buffer -> view<{TM}x20xi32>
      %w_stage = buffer.view %lds[%w_stage_offset] : buffer -> view<{TN}x20xi32>
      %wave_result_offset = index.scale %subgroup, %wave_result_bytes : index, offset -> offset
      %result_view = buffer.view %lds[%wave_result_offset] : buffer -> view<16x16xi32>

      // Staging map: packet p = workitem + 256*i covers row p/4, quad column (p%4)*4; i = 0..3 are A rows 0..255, i = 4, 5 are W rows 0..127.
      %st_sub = index.rem %workitem, %c4 : index
      %st_quad = index.mul %st_sub, %c4 : index
      %st_row_base = index.div %workitem, %c4 : index
      %k_quad_limit = index.sub %k_quads, %c4 : index
    """
    for i in range(A_PACKETS):
        K += f"  %st_arow{i} = index.add %st_row_base, %c{64 * i} : index\n" if i else "  %st_arow0 = index.add %st_row_base, %c0 : index\n"
        K += f"  %a_m{i} = index.add %base_m, %st_arow{i} : index\n  %a_ok{i} = index.cmp ult, %a_m{i}, %m_bounded : index\n"
        K += f"  %a_safe{i} = scf.select %a_ok{i}, %a_m{i}, %c0 : index\n  %a_row{i} = index.assume %a_safe{i} [lt(%a_safe{i}, %m_bounded)] : index\n"
    for i in range(PACKETS - A_PACKETS):
        K += f"  %st_wrow{i} = index.add %st_row_base, %c{64 * i} : index\n" if i else "  %st_wrow0 = index.add %st_row_base, %c0 : index\n"
        K += f"  %w_n{i} = index.add %base_n, %st_wrow{i} : index\n  %w_row{i} = index.assume %w_n{i} [lt(%w_n{i}, %n_size)] : index\n"
    K += "\n  // Operand rows this lane reads: A rows wave_row + 16i + lane16, W rows wave_col + 16j + lane16.\n"
    for i in range(FM):
        K += f"  %fa{i} = index.add %wave_row, %lane16 : index\n" if i == 0 else f"  %fa{i} = index.add %fa0, %c{16 * i} : index\n"
    for j in range(FN):
        K += f"  %fb{j} = index.add %wave_col, %lane16 : index\n" if j == 0 else f"  %fb{j} = index.add %fb0, %c{16 * j} : index\n"
    K += """
      %acc_init = vector.fragment<init> %zero_i32x8 shape [%m, %n] : vector<8xi32>

      // Gather of the first k step into registers.
      %kq_first = index.assume %st_quad [le(%st_quad, %k_quad_limit), mul(%st_quad, 4)] : index
    """
    def a_load(i, kq, ind, tag):
        return (f"{ind}%{tag}a{i} = scf.if %a_ok{i}_load -> ({V4}) {{\n" if False else "") + \
               f"{ind}%{tag}a{i} = scf.if %{tag}ok{i} -> ({V4}) {{\n{ind}  %v = vector.load %a_view[%a_row{i}, {kq}] : view<[%m_bounded]x[%k_quads]xi32> -> {V4}\n{ind}  scf.yield %v : {V4}\n{ind}}} else {{\n{ind}  scf.yield %zero_i32x4 : {V4}\n{ind}}}\n"
    for i in range(A_PACKETS):
        K += f"  %gok{i} = index.add %c0, %c0 : index\n" if False else ""
    for i in range(A_PACKETS):
        K += f"  %ga{i} = scf.if %a_ok{i} -> ({V4}) {{\n    %v = vector.load %a_view[%a_row{i}, %kq_first] : view<[%m_bounded]x[%k_quads]xi32> -> {V4}\n    scf.yield %v : {V4}\n  }} else {{\n    scf.yield %zero_i32x4 : {V4}\n  }}\n"
    for i in range(PACKETS - A_PACKETS):
        K += f"  %gw{i} = vector.load %w_view[%w_row{i}, %kq_first] : view<[%n_size]x[%k_quads]xi32> -> {V4}\n"
    carried = ", ".join([f"%acc{x}" for x in ACC] + [f"%a_last{i}" for i in range(A_PACKETS)] + [f"%w_last{i}" for i in range(PACKETS - A_PACKETS)])
    inits = ", ".join([f"%r{x} = %acc_init : {V8}" for x in ACC] + [f"%ca{i} = %ga{i} : {V4}" for i in range(A_PACKETS)] + [f"%cw{i} = %gw{i} : {V4}" for i in range(PACKETS - A_PACKETS)])
    types = ", ".join([V8] * len(ACC) + [V4] * PACKETS)
    K += f"""
      {carried} = scf.for %k_base = [%c0 to %k_size step %c128]({inits}) -> ({types}) {{
        // Stage what we were handed.
    """
    for i in range(A_PACKETS):
        K += f"    vector.store %ca{i}, %a_stage[%st_arow{i}, %st_quad] : {V4}, view<{TM}x20xi32>\n"
    for i in range(PACKETS - A_PACKETS):
        K += f"    vector.store %cw{i}, %w_stage[%st_wrow{i}, %st_quad] : {V4}, view<{TN}x20xi32>\n"
    K += """    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)

        // Prefetch the next step (zero past K) while the WMMAs run on this one.
        %k_next = index.add %k_base, %c128 : index
        %in_k = index.cmp ult, %k_next, %k_size : index
        %kq_next0 = index.div %k_next, %c8 : index
        %kq_slot = index.add %kq_next0, %st_quad : index
        %kq_safe = scf.select %in_k, %kq_slot, %st_quad : index
        %kq_next = index.assume %kq_safe [le(%kq_safe, %k_quad_limit), mul(%kq_safe, 4)] : index
    """
    for i in range(A_PACKETS):
        K += f"    %load_a{i} = scalar.andi %in_k, %a_ok{i} : i1\n"
        K += f"    %na{i} = scf.if %load_a{i} -> ({V4}) {{\n      %v = vector.load %a_view[%a_row{i}, %kq_next] : view<[%m_bounded]x[%k_quads]xi32> -> {V4}\n      scf.yield %v : {V4}\n    }} else {{\n      scf.yield %zero_i32x4 : {V4}\n    }}\n"
    for i in range(PACKETS - A_PACKETS):
        K += f"    %nw{i} = scf.if %in_k -> ({V4}) {{\n      %v = vector.load %w_view[%w_row{i}, %kq_next] : view<[%n_size]x[%k_quads]xi32> -> {V4}\n      scf.yield %v : {V4}\n    }} else {{\n      scf.yield %zero_i32x4 : {V4}\n    }}\n"
    K += "\n    // Eight 16-wide sub-steps over the staged 64 bytes: 4 A + 4 W runs, 16 WMMAs each.\n"
    prev = {x: f"%r{x}" for x in ACC}
    for s in range(8):
        for i in range(FM):
            K += f"    %da{i}_{s} = vector.load %a_stage[%fa{i}, %c{2*s}] : view<{TM}x20xi32> -> {V2}\n"
        for j in range(FN):
            K += f"    %db{j}_{s} = vector.load %w_stage[%fb{j}, %c{2*s}] : view<{TN}x20xi32> -> {V2}\n"
        for i in range(FM):
            K += f"    %la{i}_{s} = vector.fragment<lhs> %da{i}_{s} shape [%m, %k] using {{schema = %i4_schema : encoding<schema>}} : {V2}\n"
        for j in range(FN):
            K += f"    %rb{j}_{s} = vector.fragment<rhs> %db{j}_{s} shape [%k, %n] using {{schema = %i4_schema : encoding<schema>}} : {V2}\n"
        for i in range(FM):
            for j in range(FN):
                x = f"{i}{j}"
                K += f"    %o{x}_{s} = vector.mma %la{i}_{s}, %rb{j}_{s}, {prev[x]} : {V2}, {V2}, {V8}\n"
                prev[x] = f"%o{x}_{s}"
    yields = ", ".join([prev[x] for x in ACC] + [f"%na{i}" for i in range(A_PACKETS)] + [f"%nw{i}" for i in range(PACKETS - A_PACKETS)])
    K += f"""    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)
        scf.yield {yields} : {types}
      }}

      // Publish through LDS. Each lane takes two vector4 slices of each staged 16x16 tile.
      %publish_row0 = index.div %lane, %c4 : index
      %publish_col_group = index.rem %lane, %c4 : index
      %publish_col = index.mul %publish_col_group, %c4 : index
      %publish_col_half = index.mul %publish_col_group, %c2 : index
      %one_f32 = scalar.constant 1.0 : f32
      %zero_f32 = scalar.constant 0.0 : f32
      %one4 = vector.splat %one_f32 : vector<4xf32>
      %zero4 = vector.splat %zero_f32 : vector<4xf32>
      %up_stage_offset = index.constant 1024 : offset
      %wave_up_offset = index.add %wave_result_offset, %up_stage_offset : offset
      %up_view = buffer.view %lds[%wave_up_offset] : buffer -> view<16x16xi32>
    """
    # the fragment chosen for iteration f, as a select chain
    def chain(name, pick):
        text = ""; sel = None
        for f in range(16):
            if pick(f) is None: continue
            if sel is None:
                sel = f"%acc{pick(f)}"; continue
            text += f"        %{name}_is{f} = index.cmp eq, %step, %cf{f} : index\n        %{name}_p{f} = scf.select %{name}_is{f}, %acc{pick(f)}, {sel} : {V8}\n"
            sel = f"%{name}_p{f}"
        return text, sel
    if mode in ("plain", "resid"):
        K += "      scf.for %step = [%c0 to %c16 step %c1] {\n        %fi = index.div %step, %c4 : index\n        %fj = index.rem %step, %c4 : index\n"
        text, sel = chain("g", lambda f: ACC[f])
        K += text
        K += f"""        vector.fragment.store<result> {sel}, %result_view[%c0, %c0] shape [%m, %n] : {V8}, view<16x16xi32>
        kernel.barrier<workgroup> scope(subgroup) ordering(acq_rel)
        %frag_row_offset = index.mul %fi, %c16 : index
        %frag_col_offset = index.mul %fj, %c16 : index
        %tile_col = index.add %wave_col, %frag_col_offset : index
        %out_col_local = index.add %tile_col, %publish_col : index
        %out_col = index.add %base_n, %out_col_local : index
        %scale_values = vector.load %scale_view[%out_col] : view<[%n_size]xf32> -> vector<4xf32>
        scf.for %half = [%c0 to %c2 step %c1] {{
          %row_offset = index.mul %half, %c8 : index
          %publish_row = index.add %publish_row0, %row_offset : index
          %values = vector.load %result_view[%publish_row, %publish_col] : view<16x16xi32> -> vector<4xi32>
          %values_f32 = vector.sitofp %values : vector<4xi32> to vector<4xf32>
          %scaled0 = vector.mulf %values_f32, %scale_values : vector<4xf32>
          %row_in_wave = index.add %frag_row_offset, %publish_row : index
          %row_local = index.add %wave_row, %row_in_wave : index
          %out_row = index.add %base_m, %row_local : index
          %writes = index.cmp ult, %out_row, %m_bounded : index
          scf.if %writes {{
            %bounded = index.assume %out_row [lt(%out_row, %m_bounded)] : index
            %a_scale_value = view.load %a_scale_view[%bounded] : view<[%m_bounded]xf32> -> f32
            %a_scale_vector = vector.splat %a_scale_value : vector<4xf32>
            %scaled = vector.mulf %scaled0, %a_scale_vector : vector<4xf32>
"""
        if mode == "plain":
            K += """            %narrow = vector.fptrunc %scaled : vector<4xf32> to vector<4xf16>
            vector.store %narrow, %c_view[%bounded, %out_col] : vector<4xf16>, view<[%m_bounded]x[%n_size]xf16>
"""
        else:
            K += """            %cls_i32 = view.load %cls_view[%bounded] : view<[%m_bounded]xi32> -> i32
            %cls_idx0 = index.cast %cls_i32 : i32 to index
            %cls_idx = index.assume %cls_idx0 [range(%cls_idx0, 0, 63), lt(%cls_idx0, %classes)] : index
            %gate_values = vector.load %gate_view[%cls_idx, %out_col] : view<[%classes]x[%n_size]xf32> -> vector<4xf32>
            %gated = vector.mulf %scaled, %gate_values : vector<4xf32>
            %prior = vector.load %c_view[%bounded, %out_col] : view<[%m_bounded]x[%n_size]xf32> -> vector<4xf32>
            %summed = vector.addf %prior, %gated : vector<4xf32>
            vector.store %summed, %c_view[%bounded, %out_col] : vector<4xf32>, view<[%m_bounded]x[%n_size]xf32>
"""
        K += """          }
        }
        kernel.barrier<workgroup> scope(subgroup) ordering(acq_rel)
      }
"""
    else:
        # swiglu: 8 pairs (fi, fj_gate in {0, 2}); gate = fragment (fi, fj), up = (fi, fj + 1)
        K += "      scf.for %step = [%c0 to %c8 step %c1] {\n        %fi = index.div %step, %c2 : index\n        %pj = index.rem %step, %c2 : index\n"
        tg, sg = chain("g", lambda f: ACC[(f // 2) * 4 + (f % 2) * 2] if f < 8 else None)
        tu, su = chain("u", lambda f: ACC[(f // 2) * 4 + (f % 2) * 2 + 1] if f < 8 else None)
        K += tg + tu
        K += f"""        vector.fragment.store<result> {sg}, %result_view[%c0, %c0] shape [%m, %n] : {V8}, view<16x16xi32>
        vector.fragment.store<result> {su}, %up_view[%c0, %c0] shape [%m, %n] : {V8}, view<16x16xi32>
        kernel.barrier<workgroup> scope(subgroup) ordering(acq_rel)
        %frag_row_offset = index.mul %fi, %c16 : index
        %gate_col_offset = index.mul %pj, %c32 : index
        %gate_tile_col = index.add %wave_col, %gate_col_offset : index
        %gate_col_local = index.add %gate_tile_col, %publish_col : index
        %gate_col = index.add %base_n, %gate_col_local : index
        %up_col = index.add %gate_col, %c16 : index
        %gate_scale = vector.load %scale_view[%gate_col] : view<[%n_size]xf32> -> vector<4xf32>
        %up_scale = vector.load %scale_view[%up_col] : view<[%n_size]xf32> -> vector<4xf32>
        %out_col0 = index.div %gate_col, %c2 : index
        %out_col1 = index.add %out_col0, %publish_col : index
        %out_col2 = index.sub %out_col1, %publish_col_half : index
        %out_col = index.assume %out_col2 [lt(%out_col2, %n_half)] : index
        scf.for %half = [%c0 to %c2 step %c1] {{
          %row_offset = index.mul %half, %c8 : index
          %publish_row = index.add %publish_row0, %row_offset : index
          %gate_values = vector.load %result_view[%publish_row, %publish_col] : view<16x16xi32> -> vector<4xi32>
          %up_values = vector.load %up_view[%publish_row, %publish_col] : view<16x16xi32> -> vector<4xi32>
          %gate_f32 = vector.sitofp %gate_values : vector<4xi32> to vector<4xf32>
          %up_f32 = vector.sitofp %up_values : vector<4xi32> to vector<4xf32>
          %gate_scaled0 = vector.mulf %gate_f32, %gate_scale : vector<4xf32>
          %up_scaled0 = vector.mulf %up_f32, %up_scale : vector<4xf32>
          %row_in_wave = index.add %frag_row_offset, %publish_row : index
          %row_local = index.add %wave_row, %row_in_wave : index
          %out_row = index.add %base_m, %row_local : index
          %writes = index.cmp ult, %out_row, %m_bounded : index
          scf.if %writes {{
            %bounded = index.assume %out_row [lt(%out_row, %m_bounded)] : index
            %a_scale_value = view.load %a_scale_view[%bounded] : view<[%m_bounded]xf32> -> f32
            %a_scale_vector = vector.splat %a_scale_value : vector<4xf32>
            %g = vector.mulf %gate_scaled0, %a_scale_vector : vector<4xf32>
            %u = vector.mulf %up_scaled0, %a_scale_vector : vector<4xf32>
            %neg_g = vector.subf %zero4, %g : vector<4xf32>
            %e = vector.expf<afn> %neg_g : vector<4xf32>
            %den = vector.addf %one4, %e : vector<4xf32>
            %sig = vector.divf %one4, %den : vector<4xf32>
            %silu = vector.mulf %g, %sig : vector<4xf32>
            %prod = vector.mulf %silu, %u : vector<4xf32>
            %narrow = vector.fptrunc %prod : vector<4xf32> to vector<4xf16>
            vector.store %narrow, %c_view[%bounded, %out_col] : vector<4xf16>, view<[%m_bounded]x[%n_half]xf16>
          }}
        }}
        kernel.barrier<workgroup> scope(subgroup) ordering(acq_rel)
      }}
"""
    K += """      kernel.return
    }
"""
    return K


if __name__ == "__main__":
    for mode in ("plain", "resid", "swiglu"):
        stem = {"plain": "gemm_i4_256", "resid": "gemm_i4_resid_256", "swiglu": "gemm_i4_swiglu_256"}[mode]
        (ROOT / "kernels" / f"{stem}.loom").write_text(generate(mode))
        print("wrote", stem)
