"""bf16 twins of the vision tower's f16 WMMA matmuls (kernels/matmul_{bias,resid,gelu,gelu_erf}_f16_wmma.loom ->
matmul_*_bf16_wmma.loom): W is bf16 in memory as the checkpoint stores Qwen3-VL's vision tower, A is narrowed to bf16
while it is staged into LDS (f32 in for bias/gelu/gelu_erf, f16 in for resid, exactly as the f16 twins narrow it to f16),
bf16 x bf16 -> f32 WMMA, and the outputs, epilogues, signatures and configs are the f16 twins'. The edits are anchored
full-line substitutions of the operand side; every anchor must match exactly once or the generator fails.
    python3 tools/gen_matmul_bf16.py"""
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
KINDS = ("bias", "resid", "gelu", "gelu_erf")


def twin(text: str, kind: str) -> str:
    lines = text.split("\n"); counts = {}
    def swap(anchor: str, old: str, new: str, times: int = 1):
        """On every line containing `anchor`, replace `old` by `new`; exactly `times` lines must match."""
        hit = 0
        for i, line in enumerate(lines):
            if anchor in line and old in line:
                lines[i] = line.replace(old, new); hit += 1
        assert hit == times, (kind, anchor, old, hit, times)
    # names
    for i, line in enumerate(lines):
        lines[i] = line.replace(f"matmul_{kind}_f16_wmma", f"matmul_{kind}_bf16_wmma")
    # the weight operand and the LDS stage: bf16
    swap("%w_view = buffer.view", "xf16>", "xbf16>")
    swap("%w_values = vector.load %w_view", "xf16>", "xbf16>")   # the view annotation and the vector
    swap("vector.store %w_values, %w_stage_view", "vector<4xf16>, view<64x40xf16>", "vector<4xbf16>, view<64x40xbf16>")
    swap("%a_stage_view = buffer.view", "view<64x40xf16>", "view<64x40xbf16>")
    swap("%w_stage_view = buffer.view", "view<64x40xf16>", "view<64x40xbf16>")
    swap("%w_fragment_view = buffer.view", "view<32x64xf16,", "view<32x64xbf16,")
    swap("%zero_f16x4 = vector.constant", "vector<4xf16>", "vector<4xbf16>")
    # the A operand narrowed to bf16 at staging
    swap("scf.if %m_in_range -> (vector<4xf16>)", "vector<4xf16>", "vector<4xbf16>")
    swap("scf.yield %narrow : vector<4xf16>", "vector<4xf16>", "vector<4xbf16>")
    swap("scf.yield %zero_f16x4 : vector<4xf16>", "vector<4xf16>", "vector<4xbf16>")
    swap("vector.store %a_values, %a_stage_view", "vector<4xf16>, view<64x40xf16>", "vector<4xbf16>, view<64x40xbf16>")
    if kind == "resid":   # A arrives f16: widen, then narrow to bf16
        old = "        %narrow = vector.load %a_view[%bounded, %source_k] : view<[%m_size]x[%k_size]xf16> -> vector<4xf16>"
        assert lines.count(old) == 1, (kind, "resid A load")
        i = lines.index(old)
        lines[i:i + 1] = ["        %narrow_h = vector.load %a_view[%bounded, %source_k] : view<[%m_size]x[%k_size]xf16> -> vector<4xf16>",
                          "        %narrow_w = vector.extf %narrow_h : vector<4xf16> to vector<4xf32>",
                          "        %narrow = vector.fptrunc %narrow_w : vector<4xf32> to vector<4xbf16>"]
    else:
        swap("%narrow = vector.fptrunc %wide", "to vector<4xf16>", "to vector<4xbf16>")
    # fragments and the MMA
    swap("vector.fragment.load<lhs> %a_stage_view", "view<64x40xf16> -> vector<16xf16>", "view<64x40xbf16> -> vector<16xbf16>")
    swap("vector.fragment.load<rhs> %w_fragment_view", "view<32x64xf16, %w_fragment_layout> -> vector<16xf16>", "view<32x64xbf16, %w_fragment_layout> -> vector<16xbf16>", 2)
    swap("vector.mma", "vector<16xf16>, vector<16xf16>, vector<8xf32>", "vector<16xbf16>, vector<16xbf16>, vector<8xf32>", 2)
    out = "\n".join(lines)
    assert "vector<16xf16>" not in out and "view<64x40xf16>" not in out, kind
    head = (f"// GENERATED by tools/gen_matmul_bf16.py from matmul_{kind}_f16_wmma.loom: W is bf16 in memory (the checkpoint's\n"
            f"// vision tower rows as stored), A is narrowed to bf16 at LDS staging, bf16 x bf16 -> f32 WMMA; output and epilogue as the f16 twin.\n")
    return head + out


def main():
    for kind in KINDS:
        src = ROOT / "h3/kernels" / f"matmul_{kind}_f16_wmma.loom"; out = ROOT / "h3/kernels" / f"matmul_{kind}_bf16_wmma.loom"
        out.write_text(twin(src.read_text(), kind)); print("wrote", out.name)


if __name__ == "__main__":
    main()
