"""kernels/rope*_qknorm_f16.loom: per-head RMSNorm (weight w[c]) and rotate-half RoPE on q and
k from a fused [tokens][row_stride] projection (q at 0, k at k_offset, v after k), written to
contiguous q/k/v [tokens][heads*D]. One workgroup of 256 lanes per token, a wave per head,
D/32 channels per lane; channels c < R/2 pair with c + R/2, the partner quad R/2/(D/32) lanes
away through a subgroup shuffle; channels >= R pass through. Variants:
  rope_qknorm_f16     D 128, R 96   (MiniMax H3 blocks)
  rope64_qknorm_f16   D 64,  R 48   (the video VAE decoder)
  rope128_qknorm_f16  D 128, R 128  (the Qwen3 text encoder: every channel rotated)
GENERATED; edit the generator.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VARIANTS = {"rope_qknorm_f16": (128, 96), "rope64_qknorm_f16": (64, 48), "rope128_qknorm_f16": (128, 128)}


def generate(stem: str, D: int, R: int) -> str:
    CH = D // 32                    # channels per lane
    P = (R // 2) // CH              # lanes between a channel and its partner
    NS, SYM = "h3." + stem, "h3_" + stem
    inv = 1.0 / D
    half = R // 2
    return f"""// Per-head RMSNorm (weight w[c]) and rotate-half rotary embedding, head size {D}, {R} channels
// rotated: channels c < {half} pair with c + {half}; cos/sin [tokens][{half}]. q at column 0 of the fused
// [tokens][row_stride] projection, k at k_offset, v after k; outputs contiguous [tokens][heads*{D}].
// One workgroup of 256 lanes per token, a wave per head ({CH} channels per lane), the partner quad
// {P} lanes away through a subgroup shuffle.
//
// GENERATED by tools/gen_rope.py; edit the generator.
amdgpu.target<gfx11-generic> @{SYM}_gfx11 {{subgroup_size = 32}}

config.decl @{NS}.row_stride : %value: index where [range(%value, 128, 65536), mul(%value, 128)]

config.decl @{NS}.heads : %value: index where [range(%value, 1, 256)]

config.decl @{NS}.k_offset : %value: index where [range(%value, 128, 65536), mul(%value, 128)]

config.decl @{NS}.eps : f32

kernel.def target(@{SYM}_gfx11) export("{SYM}") @{SYM}(%tokens: index) {{
  %c1 = index.constant 1 : index
  %c256 = index.constant 256 : index
  kernel.launch.config workgroups(%tokens, %c1, %c1) workgroup_size(%c256, %c1, %c1) : index
}} launch(%tokens: index, %qkv: buffer, %q_weight: buffer, %k_weight: buffer, %cos: buffer, %sin: buffer, %q_out: buffer, %k_out: buffer, %v_out: buffer) {{
  %row_stride = config.get @{NS}.row_stride : index
  %heads = config.get @{NS}.heads : index
  %k_offset = config.get @{NS}.k_offset : index
  %eps = config.get @{NS}.eps : f32
  %c0 = index.constant 0 : index
  %c1 = index.constant 1 : index
  %c7 = index.constant 7 : index
  %c8 = index.constant 8 : index
  %cch = index.constant {CH} : index
  %cp = index.constant {P} : index
  %c2p = index.constant {2 * P} : index
  %cpair_last = index.constant {half - CH} : index
  %cd = index.constant {D} : index
  %c0_offset = index.constant 0 : offset
  %i32_32 = scalar.constant 32 : i32
  %zero_f = scalar.constant 0.0 : f32
  %invd = scalar.constant {inv!r} : f32
  %tokens_b = index.assume %tokens [range(%tokens, 1, 1048576)] : index
  %token = kernel.workgroup.id<x> : index
  %row = index.assume %token [lt(%token, %tokens_b)] : index
  %wave0 = kernel.subgroup.id : index
  %wave = index.assume %wave0 [range(%wave0, 0, 7)] : index
  %lane = kernel.subgroup.lane.id : index
  %lane_col = index.mul %lane, %cch : index
  %qk_heads = index.add %heads, %heads : index
  %heads_total = index.add %qk_heads, %heads : index
  %rounds0 = index.add %heads_total, %c7 : index
  %rounds = index.div %rounds0, %c8 : index
  %qkv_global = buffer.assume.memory_space<global> %qkv : buffer
  %qo_global = buffer.assume.memory_space<global> %q_out : buffer
  %ko_global = buffer.assume.memory_space<global> %k_out : buffer
  %vo_global = buffer.assume.memory_space<global> %v_out : buffer
  %width = index.mul %heads, %cd : index
  %qw_global = buffer.assume.memory_space<global> %q_weight : buffer
  %kw_global = buffer.assume.memory_space<global> %k_weight : buffer
  %cos_global = buffer.assume.memory_space<global> %cos : buffer
  %sin_global = buffer.assume.memory_space<global> %sin : buffer
  %qkv_view = buffer.view %qkv_global[%c0_offset] : buffer -> view<[%tokens_b]x[%row_stride]xf16>
  %qo_view = buffer.view %qo_global[%c0_offset] : buffer -> view<[%tokens_b]x[%width]xf16>
  %ko_view = buffer.view %ko_global[%c0_offset] : buffer -> view<[%tokens_b]x[%width]xf16>
  %vo_view = buffer.view %vo_global[%c0_offset] : buffer -> view<[%tokens_b]x[%width]xf16>
  %v_offset = index.add %k_offset, %width : index
  %w_limit = index.sub %width, %cch : index
  %qw_view = buffer.view %qw_global[%c0_offset] : buffer -> view<{D}xf32>
  %kw_view = buffer.view %kw_global[%c0_offset] : buffer -> view<{D}xf32>
  %cos_view = buffer.view %cos_global[%c0_offset] : buffer -> view<[%tokens_b]x{half}xf32>
  %sin_view = buffer.view %sin_global[%c0_offset] : buffer -> view<[%tokens_b]x{half}xf32>
  %col_limit = index.sub %row_stride, %cch : index
  // rotate-half lane classes: 0..{P - 1} hold x1, {P}..{2 * P - 1} hold x2, the rest pass through
  %is_lo = index.cmp ult, %lane, %cp : index
  %is_pair = index.cmp ult, %lane, %c2p : index
  %up = index.add %lane, %cp : index
  %down0 = index.sub %lane, %cp : index
  %down = scf.select %is_pair, %down0, %lane : index
  %partner0 = scf.select %is_lo, %up, %down : index
  %partner1 = index.assume %partner0 [range(%partner0, 0, 31)] : index
  %partner = index.cast %partner1 : index to i32
  %pair_lane0 = scf.select %is_lo, %lane, %c0 : index
  %pair_lane1 = index.sub %lane, %cp : index
  %pair_lane2 = scf.select %is_lo, %pair_lane0, %pair_lane1 : index
  %pair_lane3 = scf.select %is_pair, %pair_lane2, %c0 : index
  %pair_col0 = index.mul %pair_lane3, %cch : index
  %pair_col = index.assume %pair_col0 [le(%pair_col0, %cpair_last), mul(%pair_col0, {CH})] : index
  scf.for %r = [%c0 to %rounds step %c1] {{
    %r8 = index.mul %r, %c8 : index
    %head = index.add %r8, %wave : index
    %active = index.cmp ult, %head, %heads_total : index
    scf.if %active {{
      %is_q = index.cmp ult, %head, %heads : index
      %is_v = index.cmp uge, %head, %qk_heads : index
      %k_head0 = index.sub %head, %heads : index
      %k_head1 = scf.select %is_q, %c0, %k_head0 : index
      %k_head = index.assume %k_head1 [range(%k_head1, 0, 255)] : index
      %v_head0 = index.sub %head, %qk_heads : index
      %v_head1 = scf.select %is_v, %v_head0, %c0 : index
      %v_head = index.assume %v_head1 [range(%v_head1, 0, 255)] : index
      %q_base = index.mul %head, %cd : index
      %k_base0 = index.mul %k_head, %cd : index
      %k_base = index.add %k_offset, %k_base0 : index
      %base_qk = scf.select %is_q, %q_base, %k_base : index
      %v_base0 = index.mul %v_head, %cd : index
      %v_base = index.add %v_offset, %v_base0 : index
      %base = scf.select %is_v, %v_base, %base_qk : index
      %col0 = index.add %base, %lane_col : index
      %col = index.assume %col0 [le(%col0, %col_limit), mul(%col0, {CH})] : index
      %v16 = vector.load %qkv_view[%row, %col] : view<[%tokens_b]x[%row_stride]xf16> -> vector<{CH}xf16>
      scf.if %is_v {{
        %vc0 = index.add %v_base0, %lane_col : index
        %vc = index.assume %vc0 [le(%vc0, %w_limit), mul(%vc0, {CH})] : index
        vector.store %v16, %vo_view[%row, %vc] : vector<{CH}xf16>, view<[%tokens_b]x[%width]xf16>
      }} else {{
        %v = vector.extf %v16 : vector<{CH}xf16> to vector<{CH}xf32>
        %sq = vector.mulf %v, %v : vector<{CH}xf32>
        %lane_ss = vector.reduce<addf> %sq, %zero_f : vector<{CH}xf32>, f32
        %ss = kernel.subgroup.reduce<addf> %lane_ss : f32
        %mean = scalar.mulf %ss, %invd : f32
        %mean_eps = scalar.addf %mean, %eps : f32
        %rinv = scalar.rsqrtf %mean_eps : f32
        %rinv_v = vector.splat %rinv : vector<{CH}xf32>
        %normed = vector.mulf %v, %rinv_v : vector<{CH}xf32>
        %w_q = vector.load %qw_view[%lane_col] : view<{D}xf32> -> vector<{CH}xf32>
        %w_k = vector.load %kw_view[%lane_col] : view<{D}xf32> -> vector<{CH}xf32>
        %w = scf.if %is_q -> (vector<{CH}xf32>) {{
          scf.yield %w_q : vector<{CH}xf32>
        }} else {{
          scf.yield %w_k : vector<{CH}xf32>
        }}
        %x = vector.mulf %normed, %w : vector<{CH}xf32>
        %px, %ok = kernel.subgroup.shuffle<index> %x, %partner, %i32_32 : vector<{CH}xf32>, i32, i32
        %c = vector.load %cos_view[%row, %pair_col] : view<[%tokens_b]x{half}xf32> -> vector<{CH}xf32>
        %s = vector.load %sin_view[%row, %pair_col] : view<[%tokens_b]x{half}xf32> -> vector<{CH}xf32>
        // x1' = x1 cos - x2 sin (the lo lanes, partner x2); x2' = x1 sin + x2 cos (the hi lanes)
        %xc = vector.mulf %x, %c : vector<{CH}xf32>
        %ps = vector.mulf %px, %s : vector<{CH}xf32>
        %lo_out = vector.subf %xc, %ps : vector<{CH}xf32>
        %hi_out = vector.addf %xc, %ps : vector<{CH}xf32>
        %pair_out = scf.if %is_lo -> (vector<{CH}xf32>) {{
          scf.yield %lo_out : vector<{CH}xf32>
        }} else {{
          scf.yield %hi_out : vector<{CH}xf32>
        }}
        %out = scf.if %is_pair -> (vector<{CH}xf32>) {{
          scf.yield %pair_out : vector<{CH}xf32>
        }} else {{
          scf.yield %x : vector<{CH}xf32>
        }}
        %out16 = vector.fptrunc %out : vector<{CH}xf32> to vector<{CH}xf16>
        scf.if %is_q {{
          %qc0 = index.add %q_base, %lane_col : index
          %qc = index.assume %qc0 [le(%qc0, %w_limit), mul(%qc0, {CH})] : index
          vector.store %out16, %qo_view[%row, %qc] : vector<{CH}xf16>, view<[%tokens_b]x[%width]xf16>
        }} else {{
          %kc0 = index.add %k_base0, %lane_col : index
          %kc = index.assume %kc0 [le(%kc0, %w_limit), mul(%kc0, {CH})] : index
          vector.store %out16, %ko_view[%row, %kc] : vector<{CH}xf16>, view<[%tokens_b]x[%width]xf16>
        }}
      }}
    }}
  }}
  kernel.return
}}
"""


if __name__ == "__main__":
    for stem, (D, R) in VARIANTS.items():
        (ROOT / "kernels" / f"{stem}.loom").write_text(generate(stem, D, R))
        print("wrote", stem)
